# Funcs

In [1]:
import json
import os

def read_json(file_path):
    """Reads a JSON file and returns the data."""
    with open(file_path, "r", encoding="utf-8") as file:
        data = json.load(file)
    return data

def save_json(data, file_path, indent=4):
    """Saves data to a JSON file."""
    with open(file_path, "w", encoding="utf-8") as file:
        json.dump(data, file, indent=indent)

def read_html_files(folder_path):
    """Reads all HTML files in a folder and returns a dictionary with filenames as keys and file contents as values."""
    html_dict = {}

    for file_name in os.listdir(folder_path):
        if file_name.endswith(".html"):
            file_path = os.path.join(folder_path, file_name)
            year = int(file_name[:-5].split('_')[0])
            id_in_year = int(file_name[:-5].split('_')[1])
            with open(file_path, "r", encoding="utf-8") as file:
                html_dict[(year, id_in_year)] = file.read()
    
    return html_dict

# Merging

In [2]:
semi_cleaned = read_json('semi_cleaned_docs.json')
the_rest = read_json('the_rest_updated 1.json')

In [3]:
len(semi_cleaned)

132

In [4]:
len(the_rest)

38

In [5]:
merged = semi_cleaned + the_rest

for merged_doc in merged:
    print(merged_doc['id'])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170

In [6]:
save_json(merged, 'final_merged.json')

# Extracting Gold pieces

In [7]:
merged_ = read_json('final_merged.json')

In [8]:
sample = merged_[0:1]

In [9]:
sample[0]['data']['html']

'<document>\n<type>EX-10.1</type>\n<sequence>2</sequence>\n<filename>exhibit101creditagreement.htm</filename>\n<description>EX-10.1</description>\n<text>\n<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n\n<!-- Document created using Wdesk -->\n<!-- Copyright 2022 Workiva -->\n<title>Document</title><div id="i96ac4f6ed0ce43f083deb4a266dd81e8_1"></div><div style="min-height:72pt;width:100%"><div style="margin-bottom:0.12pt;text-align:right;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:700;line-height:100%">EXHIBIT 10.1</font></div></div><div style="margin-bottom:0.12pt;text-align:justify;text-indent:0.36pt"><table style="border-collapse:collapse;display:inline-table;margin-bottom:5pt;vertical-align:text-bottom;width:100.000%"><tr><td style="width:1.0%"></td><td style="width:98.900%"></td><td style="width:0.1%"></td></tr><tr style="height:32pt"><td colspan="3" style="border-top:10pt double #000000;padding:0 1pt"><div style="margin-bottom:6pt;padding-left:2.75pt;padding-right:2.75pt;text-align:justify;text-indent:36pt"><font><br/></font></div></td></tr></table></div><div style="margin-bottom:6pt;text-align:justify;text-indent:36pt"><font><br/></font></div><div style="margin-bottom:6pt;text-align:justify;text-indent:36pt"><font><br/></font></div><div style="margin-bottom:6pt;text-align:justify;text-indent:36pt"><font><br/></font></div><div style="margin-bottom:12pt;margin-top:12pt;text-align:center"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:700;line-height:100%">CREDIT AGREEMENT</font></div><div style="margin-bottom:12pt;text-align:center"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">dated as of January 10, 2022</font></div><div style="margin-bottom:12pt;text-align:center"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">among</font></div><div style="text-align:center"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:700;line-height:100%">FRANKLIN RESOURCES, INC.,</font></div><div style="margin-bottom:12pt;text-align:center"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">as the Borrower,</font></div><div style="margin-bottom:12pt;text-align:center"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:700;line-height:100%">BANK OF AMERICA, N.A.,</font><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%"><br/>as Administrative Agent,</font></div><div style="margin-bottom:12pt;text-align:center"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">and</font></div><div style="text-align:center"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">the Lenders party hereto</font></div><div style="text-align:center"><font><br/></font></div><div style="text-align:center"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:700;line-height:100%">BANK OF AMERICA, N.A.,</font></div><div style="text-align:center"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">as</font></div><div style="text-align:center"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">Sole Lead Arranger and Sole Bookrunner</font></div><div style="text-align:center"><font><br/></font></div><div style="text-align:center"><font><br/></font></div><div style="text-align:center"><font><br/></font></div><div style="margin-bottom:0.12pt;text-align:justify;text-indent:0.36pt"><table style="border-collapse:collapse;display:inline-table;margin-bottom:5pt;vertical-align:text-bottom;width:100.000%"><tr><td style="width:1.0%"></td><td style="width:98.900%"></td><td style="width:0.1%"></td></tr><tr style="height:26pt"><td colspan="3" style="border-bottom:10pt double #000000;padding:0 1pt"></td></tr></table></div><div style="height:72pt;position:relative;width:100%"><div style="bottom:0;position:absolute;width:100%"><div style="text-indent:0.36pt"><font style="color:#000000;font-family:\'Tahoma\',sans-serif;font-size:8pt;font-weight:400;line-height:125%">\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0</font></div></div></div><div id="i96ac4f6ed0ce43f083deb4a266dd81e8_32"></div><hr style="page-break-after:always"/><div style="min-height:72pt;width:100%"><div style="margin-bottom:0.12pt;text-align:justify;text-indent:0.36pt"><font><br/></font></div></div><div style="margin-bottom:0.12pt;text-align:center;text-indent:0.36pt"><font><br/></font></div><div style="text-align:center"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:700;line-height:100%">TABLE OF CONTENTS</font></div><div style="margin-bottom:0.12pt;text-align:justify;text-indent:0.36pt"><table style="border-collapse:collapse;display:inline-table;margin-bottom:5pt;vertical-align:text-bottom;width:100.000%"><tr><td style="width:1.0%"></td><td style="width:15.726%"></td><td style="width:0.1%"></td><td style="width:0.1%"></td><td style="width:0.601%"></td><td style="width:0.1%"></td><td style="width:1.0%"></td><td style="width:68.291%"></td><td style="width:0.1%"></td><td style="width:1.0%"></td><td style="width:11.882%"></td><td style="width:0.1%"></td></tr><tr><td colspan="3" style="padding:2px 1pt;text-align:right;text-indent:0.36pt;vertical-align:top"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%;text-decoration:underline">Section</font></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%;text-decoration:underline">Page</font></td></tr><tr><td colspan="3" style="padding:2px 3.75pt 2px 1pt;text-align:right;text-indent:0.36pt;vertical-align:top"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">ARTICLE I</font></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:justify;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">DEFINITIONS AND ACCOUNTING TERMS</font></div></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">1</font></div></td></tr><tr><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:0.12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:right;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">1.01</font></div></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:justify;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">Defined Terms</font></div></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">1</font></div></td></tr><tr><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:0.12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:right;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">1.02</font></div></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:justify;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">Other Interpretive Provisions</font></div></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">20</font></div></td></tr><tr><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:0.12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:right;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">1.03</font></div></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:justify;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">Accounting Terms.</font></div></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">21</font></div></td></tr><tr><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:0.12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:right;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">1.04</font></div></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:justify;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">Rounding</font></div></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">22</font></div></td></tr><tr><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:0.12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:right;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">1.05</font></div></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:justify;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">Times of Day</font></div></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">22</font></div></td></tr><tr><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:0.12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:right;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">1.06</font></div></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:justify;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">Interest Rates</font></div></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">22</font></div></td></tr><tr><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:0.12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:right;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">ARTICLE II</font></div></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:justify;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">THE COMMITMENTS AND CREDIT EXTENSIONS</font></div></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">22</font></div></td></tr><tr><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:0.12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:right;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">2.01</font></div></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:justify;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">Committed Loans</font></div></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">22</font></div></td></tr><tr><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:0.12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:right;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">2.02</font></div></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:justify;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">Borrowings, Conversions and Continuations of Committed Loans.</font></div></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">23</font></div></td></tr><tr><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:0.12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:right;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">2.03</font></div></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:justify;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">[Reserved].</font></div></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">24</font></div></td></tr><tr><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:0.12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:right;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">2.04</font></div></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:justify;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">[Reserved].</font></div></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">24</font></div></td></tr><tr><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:0.12pt;padding-left:2.75pt;padding-right:2.75pt;text-align:right;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">2.05</font></div></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">Prepayments.</font></div></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-align:top"><div style="margin-bottom:12pt;padding-left:2.75pt;padding-right:2.75pt;text-indent:0.36pt"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">24</font></div></td></tr><tr><td colspan="3" style="padding:2px 3.75pt 2px 1pt;text-align:right;text-indent:36pt;vertical-align:top"><font style="color:#000000;font-family:\'Times New Roman\',sans-serif;font-size:11pt;font-weight:400;line-height:100%">2.06</font></td><td colspan="3" style="padding:0 1pt"></td><td colspan="3" style="padding:2px 1pt;text-align:left;vertical-al

In [10]:
sample[0]['annotations'][0]

{'id': 1,
 'completed_by': 1,
 'result': [{'value': {'start': '/document[1]/text[1]/div[886]/font[1]/text()[1]',
    'startOffset': 0,
    'end': '/document[1]/text[1]/div[886]/font[1]/text()[1]',
    'endOffset': 24,
    'globalOffsets': {'start': 305599, 'end': 305623},
    'text': 'FRANKLIN RESOURCES, INC.',
    'hypertextlabels': ['Organization Name']},
   'id': 'aaaaaaaaaa',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[890]/font[1]/text()[1]',
    'startOffset': 7,
    'end': '/document[1]/text[1]/div[890]/font[1]/text()[1]',
    'endOffset': 20,
    'globalOffsets': {'start': 305669, 'end': 305682},
    'text': 'Mark Constant',
    'hypertextlabels': ['Person Name']},
   'id': 'aaaaaaaaab',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[891]/font[1]/text()[1]',
    'startOffset': 8,
    'end': '/document[1]/text[1]/div[891]/font[1]/text()[1]',
    'endOffset': 22,
    'globalOffsets': {'start': 305690, 'end': 305704},
    'text': 'Vice President',
    'hypertextlabels': ['Person Position']},
   'id': 'aaaaaaaaac',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[891]/font[1]/text()[1]',
    'startOffset': 27,
    'end': '/document[1]/text[1]/div[891]/font[1]/text()[1]',
    'endOffset': 36,
    'globalOffsets': {'start': 305709, 'end': 305718},
    'text': 'Treasurer',
    'hypertextlabels': ['Person Position']},
   'id': 'aaaaaaaaad',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[897]/font[1]/text()[1]',
    'startOffset': 0,
    'end': '/document[1]/text[1]/div[897]/font[1]/text()[1]',
    'endOffset': 21,
    'globalOffsets': {'start': 305758, 'end': 305779},
    'text': 'BANK OF AMERICA, N.A.',
    'hypertextlabels': ['Organization Name']},
   'id': 'aaaaaaaaae',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[897]/font[4]/text()[1]',
    'startOffset': 3,
    'end': '/document[1]/text[1]/div[897]/font[4]/text()[1]',
    'endOffset': 23,
    'globalOffsets': {'start': 305784, 'end': 305804},
    'text': 'Administrative Agent',
    'hypertextlabels': ['Organization Role']},
   'id': 'aaaaaaaaaf',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[901]/font[1]/text()[1]',
    'startOffset': 7,
    'end': '/document[1]/text[1]/div[901]/font[1]/text()[1]',
    'endOffset': 27,
    'globalOffsets': {'start': 305857, 'end': 305877},
    'text': 'Alexandra M. Knights',
    'hypertextlabels': ['Person Name']},
   'id': 'aaaaaaaaag',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[902]/font[1]/text()[1]',
    'startOffset': 10,
    'end': '/document[1]/text[1]/div[902]/font[1]/text()[1]',
    'endOffset': 30,
    'globalOffsets': {'start': 305887, 'end': 305907},
    'text': 'Authorized Signatory',
    'hypertextlabels': ['Person Position']},
   'id': 'aaaaaaaaah',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[907]/font[1]/text()[1]',
    'startOffset': 0,
    'end': '/document[1]/text[1]/div[907]/font[1]/text()[1]',
    'endOffset': 21,
    'globalOffsets': {'start': 305946, 'end': 305967},
    'text': 'BANK OF AMERICA, N.A.',
    'hypertextlabels': ['Organization Name']},
   'id': 'aaaaaaaaai',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[908]/font[1]/text()[1]',
    'startOffset': 5,
    'end': '/document[1]/text[1]/div[908]/font[1]/text()[1]',
    'endOffset': 11,
    'globalOffsets': {'start': 305974, 'end': 305980},
    'text': 'Lender',
    'hypertextlabels': ['Organization Role']},
   'id': 'aaaaaaaaaj',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[912]/font[1]/text()[1]',
    'startOffset': 7,
    'end': '/document[1]/text[1]/div[912]/font[1]/text()[1]',
    'endOffset': 27,
    'globalOffsets': {'start': 306033, 'end': 306053},
    'text': 'Alexandra M. Knights',
    'hypertextlabels': ['Person Name']},
   'id': 'aaaaaaaaak',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[913]/font[1]/text()[1]',
    'startOffset': 10,
    'end': '/document[1]/text[1]/div[913]/font[1]/text()[1]',
    'endOffset': 30,
    'globalOffsets': {'start': 306063, 'end': 306083},
    'text': 'Authorized Signatory',
    'hypertextlabels': ['Person Position']},
   'id': 'aaaaaaaaal',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
    'startOffset': 8,
    'end': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
    'endOffset': 29,
    'globalOffsets': {'start': 8028, 'end': 8049},
    'text': 'Bank of America, N.A.',
    'hypertextlabels': ['Organization Name']},
   'id': 'aaaaaaaaam',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
    'startOffset': 94,
    'end': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
    'endOffset': 99,
    'globalOffsets': {'start': 8114, 'end': 8119},
    'text': 'lead ',
    'hypertextlabels': ['Organization Sub-Role']},
   'id': 'aaaaaaaaan',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
    'startOffset': 99,
    'end': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
    'endOffset': 108,
    'globalOffsets': {'start': 8119, 'end': 8128},
    'text': 'arranger ',
    'hypertextlabels': ['Organization Role']},
   'id': 'aaaaaaaaao',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
    'startOffset': 117,
    'end': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
    'endOffset': 127,
    'globalOffsets': {'start': 8137, 'end': 8147},
    'text': 'bookrunner',
    'hypertextlabels': ['Organization Role']},
   'id': 'aaaaaaaaap',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[65]/font[4]/text()[1]',
    'startOffset': 0,
    'end': '/document[1]/text[1]/div[65]/font[4]/text()[1]',
    'endOffset': 8,
    'globalOffsets': {'start': 4991, 'end': 4999},
    'text': 'Borrower',
    'hypertextlabels': ['Organization Role']},
   'id': 'aaaaaaaaaq',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[65]/font[3]/text()[1]',
    'startOffset': 49,
    'end': '/document[1]/text[1]/div[65]/font[3]/text()[1]',
    'endOffset': 73,
    'globalOffsets': {'start': 4936, 'end': 4960},
    'text': 'FRANKLIN RESOURCES, INC.',
    'hypertextlabels': ['Organization Name']},
   'id': 'aaaaaaaaar',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[65]/font[9]/text()[1]',
    'startOffset': 8,
    'end': '/document[1]/text[1]/div[65]/font[9]/text()[1]',
    'endOffset': 29,
    'globalOffsets': {'start': 5110, 'end': 5131},
    'text': 'BANK OF AMERICA, N.A.',
    'hypertextlabels': ['Organization Name']},
   'id': 'aaaaaaaaas',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[65]/font[11]/text()[1]',
    'startOffset': 3,
    'end': '/document[1]/text[1]/div[65]/font[11]/text()[1]',
    'endOffset': 23,
    'globalOffsets': {'start': 5136, 'end': 5156},
    'text': 'Administrative Agent',
    'hypertextlabels': ['Organization Role']},
   'id': 'aaaaaaaaat',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[10]/font[1]/text()[1]',
    'startOffset': 0,
    'end': '/document[1]/text[1]/div[10]/font[1]/text()[1]',
    'endOffset': 24,
    'globalOffsets': {'start': 127, 'end': 151},
    'text': 'FRANKLIN RESOURCES, INC.',
    'hypertextlabels': ['Organization Name']},
   'id': 'aaaaaaaaau',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[12]/font[1]/text()[1]',
    'startOffset': 0,
    'end': '/document[1]/text[1]/div[12]/font[1]/text()[1]',
    'endOffset': 21,
    'globalOffsets': {'start': 168, 'end': 189},
    'text': 'BANK OF AMERICA, N.A.',
    'hypertextlabels': ['Organization Name']},
   'id': 'aaaaaaaaav',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[16]/font[1]/text()[1]',
    'startOffset': 0,
    'end': '/document[1]/text[1]/div[16]/font[1]/text()[1]',
    'endOffset': 21,
    'globalOffsets': {'start': 243, 'end': 264},
    'text': 'BANK OF AMERICA, N.A.',
    'hypertextlabels': ['Organization Name']},
   'id': 'aaaaaaaaaw',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[11]/font[1]/text()[1]',
    'startOffset': 7,
    'end': '/document[1]/text[1]/div[11]/font[1]/text()[1]',
    'endOffset': 15,
    'globalOffsets': {'start': 159, 'end': 167},
    'text': 'Borrower',
    'hypertextlabels': ['Organization Role']},
   'id': 'aaaaaaaaax',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[12]/font[2]/text()[1]',
    'startOffset': 3,
    'end': '/document[1]/text[1]/div[12]/font[2]/text()[1]',
    'endOffset': 23,
    'globalOffsets': {'start': 194, 'end': 214},
    'text': 'Administrative Agent',
    'hypertextlabels': ['Organization Role']},
   'id': 'aaaaaaaaay',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[14]/font[1]/text()[1]',
    'startOffset': 4,
    'end': '/document[1]/text[1]/div[14]/font[1]/text()[1]',
    'endOffset': 11,
    'globalOffsets': {'start': 222, 'end': 229},
    'text': 'Lenders',
    'hypertextlabels': ['Organization Role']},
   'id': 'aaaaaaaaaz',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[18]/font[1]/text()[1]',
    'startOffset': 10,
    'end': '/document[1]/text[1]/div[18]/font[1]/text()[1]',
    'endOffset': 18,
    'globalOffsets': {'start': 277, 'end': 285},
    'text': 'Arranger',
    'hypertextlabels': ['Organization Role']},
   'id': 'aaaaaaaaaA',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[18]/font[1]/text()[1]',
    'startOffset': 28,
    'end': '/document[1]/text[1]/div[18]/font[1]/text()[1]',
    'endOffset': 38,
    'globalOffsets': {'start': 295, 'end': 305},
    'text': 'Bookrunner',
    'hypertextlabels': ['Organization Role']},
   'id': 'aaaaaaaaaB',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'value': {'start': '/document[1]/text[1]/div[18]/font[1]/text()[1]',
    'startOffset': 5,
    'end': '/document[1]/text[1]/div[18]/font[1]/text()[1]',
    'endOffset': 9,
    'globalOffsets': {'start': 272, 'end': 276},
    'text': 'Lead',
    'hypertextlabels': ['Organization Sub-Role']},
   'id': 'aaaaaaaaaC',
   'from_name': 'ner',
   'to_name': 'text',
   'type': 'hypertextlabels',
   'origin': 'manual'},
  {'from_id': 'aaaaaaaaam',
   'to_id': 'aaaaaaaaao',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaam',
   'to_id': 'aaaaaaaaap',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaao',
   'to_id': 'aaaaaaaaan',
   'type': 'relation',
   'direction': 'left'},
  {'from_id': 'aaaaaaaaar',
   'to_id': 'aaaaaaaaaq',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaab',
   'to_id': 'aaaaaaaaac',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaab',
   'to_id': 'aaaaaaaaad',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaac',
   'to_id': 'aaaaaaaaaa',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaad',
   'to_id': 'aaaaaaaaaa',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaae',
   'to_id': 'aaaaaaaaaf',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaag',
   'to_id': 'aaaaaaaaah',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaah',
   'to_id': 'aaaaaaaaae',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaai',
   'to_id': 'aaaaaaaaaj',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaak',
   'to_id': 'aaaaaaaaal',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaal',
   'to_id': 'aaaaaaaaai',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaas',
   'to_id': 'aaaaaaaaat',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaaC',
   'to_id': 'aaaaaaaaaA',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaaw',
   'to_id': 'aaaaaaaaaA',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaaw',
   'to_id': 'aaaaaaaaaB',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaaw',
   'to_id': 'aaaaaaaaaz',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaav',
   'to_id': 'aaaaaaaaay',
   'type': 'relation',
   'direction': 'right'},
  {'from_id': 'aaaaaaaaau',
   'to_id': 'aaaaaaaaax',
   'type': 'relation',
   'direction': 'right'}],
 'was_cancelled': False,
 'ground_truth': False,
 'created_at': '2025-01-27T03:00:26.800949Z',
 'updated_at': '2025-01-27T03:00:26.800997Z',
 'draft_created_at': None,
 'lead_time': 1278.878,
 'prediction': {},
 'result_count': 0,
 'unique_id': '9f582d92-3bdf-48db-8c1f-5af4e40a9793',
 'import_id': 1,
 'last_action': None,
 'task': 1,
 'project': 142,
 'updated_by': None,
 'parent_prediction': None,
 'parent_annotation': None,
 'last_created_by': None}

In [11]:
save_json(sample, 'sample.json')

In [12]:
import json
from bs4 import BeautifulSoup

def extract_and_merge_snippets_with_entities(data, padding=100):
    raw_html = data[0]["data"]["html"]
    annotations = data[0]["annotations"][0]["result"]
    soup = BeautifulSoup(raw_html, 'html.parser')
    clean_text = soup.get_text()

    raw_spans = []

    # Step 1: Get all matched annotation spans
    for ann in annotations:
        value = ann.get("value", {})
        if "text" not in value or "hypertextlabels" not in value:
            continue
        entity_text = value["text"].strip()
        label = value["hypertextlabels"]

        start_idx = 0
        while True:
            idx = clean_text.find(entity_text, start_idx)
            if idx == -1:
                break
            span_start = max(0, idx - padding)
            span_end = min(len(clean_text), idx + len(entity_text) + padding)
            raw_spans.append({
                "start": span_start,
                "end": span_end,
                "entity_start": idx,
                "entity_end": idx + len(entity_text),
                "entity_text": entity_text,
                "label": label
            })
            start_idx = idx + len(entity_text)

    # Step 2: Sort and merge overlapping spans
    if not raw_spans:
        return []

    # sort by span start
    raw_spans.sort(key=lambda x: x["start"])
    merged_snippets = []
    current = {
        "start": raw_spans[0]["start"],
        "end": raw_spans[0]["end"],
        "entities": [raw_spans[0]]
    }

    for span in raw_spans[1:]:
        if span["start"] <= current["end"]:  # overlap
            current["end"] = max(current["end"], span["end"])
            current["entities"].append(span)
        else:
            merged_snippets.append(current)
            current = {
                "start": span["start"],
                "end": span["end"],
                "entities": [span]
            }
    merged_snippets.append(current)

    # Step 3: Final output
    results = []
    for snippet in merged_snippets:
        snippet_text = clean_text[snippet["start"]:snippet["end"]]
        matched_entities = list({
            e["entity_text"] for e in snippet["entities"]
            if snippet["start"] <= e["entity_start"] < snippet["end"]
        })

        results.append({
            "context_snippet": snippet_text,
            "matched_entities": matched_entities
        })

    return results

# Example usage
snippets = extract_and_merge_snippets_with_entities(sample, padding=100)
for i, s in enumerate(snippets):
    print(f"\nSnippet {i+1}:")
    print("Matched Entities:", s["matched_entities"])
    print("Context:\n", s["context_snippet"])
    print('-' * 50)

Snippet 1:
Matched Entities: ['Administrative Agent', 'Lender', 'Lenders', 'BANK OF AMERICA, N.A.', 'FRANKLIN RESOURCES, INC.', 'Arranger', 'Borrower', 'Bookrunner', 'Lead']
Context:
 reditagreement.htm
EX-10.1




DocumentEXHIBIT 10.1CREDIT AGREEMENTdated as of January 10, 2022amongFRANKLIN RESOURCES, INC.,as the Borrower,BANK OF AMERICA, N.A.,as Administrative Agent,andthe Lenders party heretoBANK OF AMERICA, N.A.,asSole Lead Arranger and Sole Bookrunner                TABLE OF CONTENTSSectionPageARTICLE IDEFINITIONS AND ACCOUNTING TERMS11.01Defined Te
--------------------------------------------------

Snippet 2:
Matched Entities: ['Administrative Agent', 'Lender', 'Lenders']
Context:
 Commitment Fee252.10Computation of Interest and Fees262.11Evidence of Debt262.12Payments Generally; Administrative Agent’s Clawback.262.13Sharing of Payments by Lenders282.14[Reserved].282.15[Reserved].282.16[Reserved].282.17Defaulting Lenders.282.18Defaulting Lender Cure29ARTICLE IIITAXES, YIELD PROTECTION AND ILLEGALITY293.01Taxes.293.02Illegality333.03Inability
--------------------------------------------------

Snippet 3:
Matched Entities: ['Lenders', 'Lender']
Context:
 tes.333.04Increased Costs.363.05Compensation for Losses373.06Mitigation Obligations; Replacement of Lenders373.07Survival38ARTICLE IVCONDITIONS PRECEDENT TO CREDIT EXTENSIONS384.01Conditions of Initial Credi
--------------------------------------------------

Snippet 4:
Matched Entities: ['Arranger', 'Administrative Agent', 'Lender', 'Lenders']
Context:
 pplication of Funds55ARTICLE IXADMINISTRATIVE AGENT559.01Appointment and Authority559.02Rights as a Lender559.03Exculpatory Provisions55- iii -9.04Reliance by Administrative Agent569.05Delegation of Duties579.06Resignation of Administrative Agent.579.07Non-Reliance on the Administrative Agent, the Arranger and the Other Lenders589.08No Other Duties, Etc589.09Administrative Agent May File Proofs of Claim589.10Guaranty Matters599.11Certain ERISA Matters.599.12Recovery of Erroneo
--------------------------------------------------

Snippet 5:
Matched Entities: ['Lenders', 'Lender']
Context:
 ectiveness7110.11Survival of Representations and Warranties7110.12Severability7110.13Replacement of Lenders7110.14Governing Law; Jurisdiction; Etc7210.15Waiver of Jury Trial7310.16No Advisory or Fiduciary Re
--------------------------------------------------

Snippet 6:
Matched Entities: ['Administrative Agent']
Context:
  Interim Financial Statements7.01    Existing Liens7.02    Existing Subsidiary Indebtedness10.02    Administrative Agent’s Office; Certain Addresses for NoticesEXHIBITSA    Form of Committed Loan NoticeB    [Reserved]C
--------------------------------------------------

Snippet 7:
Matched Entities: ['Lenders', 'Lender']
Context:
 QuestionnaireF    [Reserved]G    [Reserved]H-1    Form of U.S. Tax Compliance Certificate – Foreign Lenders (Not Partnerships)H-2    Form of U.S. Tax Compliance Certificate – Non-U.S. Participants (Not Partn
--------------------------------------------------

Snippet 8:
Matched Entities: ['Lenders', 'Lender', 'Administrative Agent', 'BANK OF AMERICA, N.A.', 'FRANKLIN RESOURCES, INC.', 'Borrower']
Context:
 cate – Non-U.S. Participants (Partnerships)H-4    Form of U.S. Tax Compliance Certificate – Foreign Lenders (Partnerships)I    Form of Notice of Loan Prepayment- v -CREDIT AGREEMENTThis CREDIT AGREEMENT (“Agreement”) is entered into as of January 10, 2022, among FRANKLIN RESOURCES, INC., a Delaware corporation (the “Borrower”), each lender from time to time party hereto (collectively, the “Lenders” and individually, a “Lender”), and BANK OF AMERICA, N.A., as Administrative Agent.The Borrower has requested that the Lenders provide a revolving credit facility, and the Lenders are willing to do so on the terms and conditions set forth herein.In consideration of the mutual co
--------------------------------------------------

Snippet 9:
Matched Entities: ['Administrative Agent', 'Borrower', 'Lenders', 'Lender']
Context:
 ing terms shall have the meanings set forth below:“Act” has the meaning specified in Section 10.18.“Administrative Agent” means Bank of America in its capacity as administrative agent under any of the Loan Documents, or any successor administrative agent.“Administrative Agent’s Office” means the Administrative Agent’s address and, as appropriate, account as set forth on Schedule 10.02, or such other address or account as the Administrative Agent may from time to time notify in writing to the Borrower and the Lenders.“Administrative Questionnaire” means an Administrative Questionnaire in substantially the form of Exhibit E-2 or any other form approved by the Administrative Agent.“Affected Financial Institution” means (a) any EEA Financial Institution or (b) any UK Financial In
--------------------------------------------------

Snippet 10:
Matched Entities: ['Borrower']
Context:
 filiate” means, with respect to a specified Person, another Person (other than, with respect to the Borrower, an Excluded Entity of the Borrower) that directly, or indirectly through one or more intermediaries, Controls or is Controlled by or i
--------------------------------------------------

Snippet 11:
Matched Entities: ['Lenders', 'Lender']
Context:
 r common Control with the Person specified.“Aggregate Commitments” means the Commitments of all the Lenders.“Agreement” has the meaning specified in the introductory paragraph hereto.“Applicable Law” means,
--------------------------------------------------

Snippet 12:
Matched Entities: ['Bank of America, N.A.', 'Lender', 'lead', 'Arranger', 'arranger', 'bookrunner']
Context:
  such Person or to which such a Person is subject.“Applicable Percentage” means with respect to any Lender at any time, the percentage (carried out to the ninth decimal place) of the Aggregate Commitments represented by such Lender’s Commitment at such time, subject to adjustment as provided in Section 2.17.  If the commitment of each Lender to make Loans have been terminated pursuant to Section 8.02 or if the Aggregate Commitments have expired, then the Applicable Percentage of each Lender shall be determined based on the Applicable Percentage of such Lender most recently in effect, giving effect to any subsequent assignments and to any Lender’s status as a Defaulting Lender at the time of determination. The initial Applicable Percentage of each Lender is set forth opposite the name of such Lender on Schedule 2.01 or in the Assignment and Assumption pursuant to which such Lender becomes a party hereto, as applicable.“Applicable Rate” means 0.65%.“Approved Fund” means any Fund that is administered or managed by (a) a Lender, (b) an Affiliate of a Lender or (c) an entity or an Affiliate of an entity that administers or manages a Lender.“Arranger” means Bank of America, N.A., an affiliate of BofA Securities, Inc., in its capacity as sole lead arranger and sole bookrunner.“Assignment and Assumption” means an assignment and assumption entered into by a Lender and an Eligible Assignee (with the consent of any party whose consent is required by Section 10.06(
--------------------------------------------------

Snippet 13:
Matched Entities: ['Administrative Agent']
Context:
 orm (including electronic documentation generated by use of an electronic platform) approved by the Administrative Agent.“Attributable Indebtedness” means, on any date, (a) in respect of any Capital Lease of any Person,
--------------------------------------------------

Snippet 14:
Matched Entities: ['Borrower']
Context:
  a Capital Lease.“Audited Financial Statements” means the audited consolidated balance sheet of the Borrower and its Subsidiaries for the fiscal year ended December 31, 2020, and the related consolidated statements of income, stockholders’ equity and cash flows for such fiscal year of the Borrower and its Subsidiaries, including the notes thereto.“Availability Period” means the period from and i
--------------------------------------------------

Snippet 15:
Matched Entities: ['Lender']
Context:
 ate Commitments pursuant to Section 2.06, and (c) the date of termination of the commitment of each Lender to make Loans pursuant to Section 8.02.“Bail-In Action” means the exercise of any Write-Down and Co
--------------------------------------------------

Snippet 16:
Matched Entities: ['Bank of America, N.A.']
Context:
  than through liquidation, administration or other insolvency proceedings). “Bank of America” means Bank of America, N.A. and its successors.“Base Rate” means for any day a fluctuating rate per annum equal to the highest
--------------------------------------------------

Snippet 17:
Matched Entities: ['Borrower']
Context:
  of any such “employee benefit plan” or “plan”.“Bloomberg” means Bloomberg Index Services Limited. “Borrower” has the meaning specified in the introductory paragraph hereto.“Borrower Materials” has the meaning specified in Section 6.02.“Borrowing” means a Committed Borrowing.“BSBY”
--------------------------------------------------

Snippet 18:
Matched Entities: ['Administrative Agent']
Context:
 Bank Yield Index rate administered by Bloomberg (or any successor administrator satisfactory to the Administrative Agent) and published on the applicable Reuters screen page (or such other commercially available source providing such quotations as may be designated by the Administrative Agent from time to time).- 3 -“Business Day” means any day other than a Saturday, Sunday or other day on
--------------------------------------------------

Snippet 19:
Matched Entities: ['Administrative Agent']
Context:
 cial banks are authorized to close under the Laws of, or are in fact closed in, the state where the Administrative Agent’s Office is located and, if such day relates to any BSBY Rate Loan, in New York City. “Capital Leas
--------------------------------------------------

Snippet 20:
Matched Entities: ['Borrower']
Context:
 rporate demand notes, in each case which is issued by a corporation (other than an Affiliate of the Borrower) rated at least A-1 by S&P, F1 by Fitch or P-1 by Moody’s (or carrying an equivalent rating by an i
--------------------------------------------------

Snippet 21:
Matched Entities: ['Borrower', 'Lender']
Context:
 to that referenced in the applicable clause and are customarily used by corporations similar to the Borrower for cash management purposes outside the United States.“Change in Law” means the occurrence, after the date of this Agreement or, with respect to any Lender, such later date on which such Lender became a party to this Agreement, of any of the following: (a) the adoption or taking effect of any
--------------------------------------------------

Snippet 22:
Matched Entities: ['Borrower']
Context:
  right, an “option right”)), directly or indirectly, of 50% or more of the equity securities of the Borrower entitled to vote for members of the board of directors or equivalent governing body of the Borrower on a fully-diluted basis (and taking into account all such securities that such person or group has
--------------------------------------------------

Snippet 23:
Matched Entities: ['Borrower']
Context:
 nths, a majority of the members of the board of directors or other equivalent governing body of the Borrower cease to be composed of individuals (i) who were members of that board or equivalent governing body
--------------------------------------------------

Snippet 24:
Matched Entities: ['Lender', 'Borrower']
Context:
 ce with Section 10.01.“Code” means the Internal Revenue Code of 1986.“Commitment” means, as to each Lender, its obligation to make Committed Loans to the Borrower pursuant to Section 2.01 in an aggregate principal amount at any one time outstanding not to exceed the amount set forth opposite such Lender’s name on Schedule 2.01 or in the Assignment and Assumption pursuant to which such Lender becomes a party hereto, as applicable, as such amount may be adjusted from time to time in accordan
--------------------------------------------------

Snippet 25:
Matched Entities: ['Lenders', 'Lender']
Context:
  same Type and, in the case of BSBY Rate Loans, having the same Interest Period made by each of the Lenders pursuant to Section 2.01.“Committed Loan” has the meaning specified in Section 2.01.“Committed Loan
--------------------------------------------------

Snippet 26:
Matched Entities: ['Administrative Agent', 'Borrower']
Context:
  which shall be substantially in the form of Exhibit A or such other form as may be approved by the Administrative Agent (including any form on an electronic platform or electronic transmission system as shall be approved by the Administrative Agent), appropriately completed and signed by a Responsible Officer of the Borrower.“Communication” means this Agreement, any Loan Document and any document, any amendment, approval,
--------------------------------------------------

Snippet 27:
Matched Entities: ['Administrative Agent']
Context:
 ontinuation notices and length of lookback periods) as may be appropriate, in the discretion of the Administrative Agent, to reflect the adoption and implementation of such applicable rate, and to permit the administration thereof by the Administrative Agent in a manner substantially consistent with market practice (or, if the Administrative Agent determines that adoption of any portion of such market practice is not administratively feasible or
--------------------------------------------------

Snippet 28:
Matched Entities: ['Administrative Agent']
Context:
  practice for the administration of such rate exists, in such other manner of administration as the Administrative Agent determines is reasonably necessary in connection with the administration of this Agreement and any
--------------------------------------------------

Snippet 29:
Matched Entities: ['Borrower']
Context:
 at are franchise Taxes or branch profits Taxes.“Consolidated EBITDA” means, for any period, for the Borrower and its Subsidiaries on a consolidated basis, an amount equal to Consolidated Net Income for such p
--------------------------------------------------

Snippet 30:
Matched Entities: ['Borrower']
Context:
 r such period, (ii) the provision for Federal, state, local and foreign income taxes payable by the Borrower and its Subsidiaries for such period, (iii) depreciation and amortization expense, (iv) extraordinary or non-recurring expenses or losses of the Borrower and its Subsidiaries reducing such Consolidated Net Income, (v) transaction fees, costs and expense
--------------------------------------------------

Snippet 31:
Matched Entities: ['Borrower']
Context:
 ating such Consolidated Net Income: (i) Federal, state, local and foreign income tax credits of the Borrower and its Subsidiaries for such period and (ii) all non-cash items increasing Consolidated Net Income
--------------------------------------------------

Snippet 32:
Matched Entities: ['Borrower']
Context:
 ative effect of foreign currency losses; provided, that, for purposes of calculating EBITDA for the Borrower and its Subsidiaries for any period, the EBITDA of any Person (or assets or division of such Person) acquired by or disposed of by the Borrower or any of its Subsidiaries during such period shall be included (or excluded, as the case may be) o
--------------------------------------------------

Snippet 33:
Matched Entities: ['Borrower']
Context:
  of such period).“Consolidated Funded Indebtedness” means, as of any date of determination, for the Borrower and its Subsidiaries on a consolidated basis, the sum of (a) the outstanding principal amount of al
--------------------------------------------------

Snippet 34:
Matched Entities: ['Borrower']
Context:
 ding Indebtedness of the types specified in clauses (a) through (e) above of Persons other than the Borrower or any Subsidiary, and (g) the outstanding principal amount of all Indebtedness of the types referr
--------------------------------------------------

Snippet 35:
Matched Entities: ['Borrower']
Context:
 r than a joint venture that is itself a corporation or limited liability - 6 -company) in which the Borrower or a Subsidiary is a general partner or joint venturer, unless such Indebtedness is expressly made non-recourse to the Borrower or such Subsidiary. Consolidated Funded Indebtedness shall not include (i) any of the foregoing cla
--------------------------------------------------

Snippet 36:
Matched Entities: ['Borrower']
Context:
 efinition of any Excluded Entity, except to the extent there is recourse for such obligation to the Borrower or any Subsidiary (other than an Excluded Entity), (ii) any Non-Recourse Indebtedness or (iii) any
--------------------------------------------------

Snippet 37:
Matched Entities: ['Borrower']
Context:
 ness shall not be deemed outstanding.“Consolidated Interest Charges” means, for any period, for the Borrower and its Subsidiaries on a consolidated basis, the sum of (a) all interest, premium payments, amortization or write off of debt discount, fees, charges and related expenses of the Borrower and its Subsidiaries in connection with Indebtedness (including capitalized interest but excluding
--------------------------------------------------

Snippet 38:
Matched Entities: ['Borrower']
Context:
  the extent treated as interest in accordance with GAAP, and (b) the portion of rent expense of the Borrower and its Subsidiaries with respect to such period under Capital Leases that is treated as interest i
--------------------------------------------------

Snippet 39:
Matched Entities: ['Borrower']
Context:
 h restriction or encumbrance would be permitted under Section 7.01(q)) cash and Cash Equivalents of Borrower and its Subsidiaries (which, for clarity, shall not include such cash and Cash Equivalents (i) held
--------------------------------------------------

Snippet 40:
Matched Entities: ['Borrower']
Context:
 e four fiscal quarters most recently ended.“Consolidated Net Income” means, for any period, for the Borrower and its Subsidiaries on a consolidated basis, the net income of the Borrower and its Subsidiaries (excluding extraordinary gains and extraordinary losses) for that period. “Con
--------------------------------------------------

Snippet 41:
Matched Entities: ['Borrower']
Context:
 et Income” shall include the amount of dividends or distributions or other payments received by the Borrower or any Subsidiary from an Excluded Entity (but only to the extent actually received).“Contractual O
--------------------------------------------------

Snippet 42:
Matched Entities: ['Administrative Agent', 'Lender', 'Borrower']
Context:
 ate (including any Applicable Rate) otherwise applicable to such Loan plus 2% per annum.“Defaulting Lender” means, subject to Section 2.17(b), any Lender that (a) has failed to (i) fund all or any portion of its Loans within two Business Days of the date such Loans were required to be funded hereunder unless such Lender notifies the Administrative Agent and the Borrower in writing that such failure is the result of such Lender’s determination that one or more conditions precedent to funding (each of which conditions preceden
--------------------------------------------------

Snippet 43:
Matched Entities: ['Administrative Agent', 'Lender', 'Borrower']
Context:

In [8]:
import json
from bs4 import BeautifulSoup

def extract_merged_snippets_per_doc(data, padding=100):
    merged_by_doc = []

    for doc in data:
        raw_html = doc["data"]["html"]
        annotations = doc["annotations"][0]["result"]
        soup = BeautifulSoup(raw_html, 'html.parser')
        clean_text = soup.get_text()

        raw_spans = []

        for ann in annotations:
            value = ann.get("value", {})
            if "text" not in value:
                continue
            entity_text = value["text"].strip()

            start_idx = 0
            while True:
                idx = clean_text.find(entity_text, start_idx)
                if idx == -1:
                    break
                span_start = max(0, idx - padding)
                span_end = min(len(clean_text), idx + len(entity_text) + padding)
                raw_spans.append((span_start, span_end))
                start_idx = idx + len(entity_text)

        if not raw_spans:
            merged_by_doc.append("")  # empty string for this doc
            continue

        raw_spans.sort()
        merged = [raw_spans[0]]
        for start, end in raw_spans[1:]:
            last_start, last_end = merged[-1]
            if start <= last_end:
                merged[-1] = (last_start, max(last_end, end))
            else:
                merged.append((start, end))

        merged_text = ""
        for start, end in merged:
            merged_text += clean_text[start:end] + "\n\n"

        merged_by_doc.append(merged_text.strip())
        print(f"\n=== Document {doc['id']} ===")
        print(f'Doc length: {len(doc["data"]["html"])}')
        print(f'Text length: {len(merged_by_doc[-1])}')
        print(merged_by_doc[-1][:500])  # Preview first 500 chars per doc
        print("-" * 50)

    return merged_by_doc

# Usage
merged_per_doc = extract_merged_snippets_per_doc(merged_, padding=100)

for i, text in enumerate(merged_per_doc):
    print(f"\n=== Document {i + 1} ===")
    print(f'Doc length: {len(merged_[i]["data"]["html"])}')
    print(f'Text length: {len(text)}')
    print(text[:500])  # Preview first 500 chars per doc
    print("-" * 50)

=== Document 1 ===
Doc length: 828619
Text length: 174998
reditagreement.htm
EX-10.1




DocumentEXHIBIT 10.1CREDIT AGREEMENTdated as of January 10, 2022amongFRANKLIN RESOURCES, INC.,as the Borrower,BANK OF AMERICA, N.A.,as Administrative Agent,andthe Lenders party heretoBANK OF AMERICA, N.A.,asSole Lead Arranger and Sole Bookrunner                TABLE OF CONTENTSSectionPageARTICLE IDEFINITIONS AND ACCOUNTING TERMS11.01Defined Te

Commitment Fee252.10Computation of Interest and Fees262.11Evidence of Debt262.12Payments Generally; Administrative Agent’s
--------------------------------------------------

=== Document 2 ===
Doc length: 607168
Text length: 226010
10.1

Exhibit 10.1
EXECUTION VERSION

CREDIT AGREEMENT  DATED
AS OF JANUARY 14, 2022  AMONG
DICKS SPORTING GOODS, INC.,
as the Borrower,  THE
LENDERS FROM TIME TO TIME PARTIES HERETO,  and
WELLS FARGO BANK, NATIONAL ASSOCIATION,
as Administrative Agent and an Issuing Lender
WELLS FARGO SECURITIES, LLC,
and  BOFA SECURITIES,
INC.,  as Joint Lead Arrangers and Joint Bookrunners
BANK OF AMERICA, N.A.,
as Syndication Agent
PNC BANK, NATIONAL ASSOCIATION,
TD SECURITIES (USA) LLC,
a
--------------------------------------------------

=== Document 3 ===
Doc length: 1147753
Text length: 266460
w Term Facility
CUSIP Number: 86613YAC7

CREDIT AGREEMENT

Dated as of January 13, 2022

among

SUMMIT JV MR 2, LLC,

SUMMIT JV MR 3, LLC

and

SUMMIT NCI NOLA BR 184, LLC

as Borrowers,

SUMMIT HOSPITALITY JV, LP

as Parent,

CERTAIN SUBSIDIARIES OF THE BORROWERS
FROM TIME TO TIME PARTY HERETO,

as Guarantors,

THE INITIAL LENDERS NAMED HEREIN,

as Initial Lenders,

BANK OF AMERICA, N.A.,

as Administrative Agent,

and

BofA SECURITIES, INC.

and
WELLS FARGO SECURITIES, LLC,

--------------------------------------------------

=== Document 4 ===
Doc length: 2419209
Text length: 682128
CREDIT AGREEMENT
Dated as of January 30, 2013  among  BRIGHT HORIZONS FAMILY SOLUTIONS LLC,
as Borrower,
BRIGHT HORIZONS CAPITAL CORP.,  as Holdings,  GOLDMAN SACHS BANK USA,
as Administrative Agent, Swing Line Lender,  L/C Issuer, Joint Lead Arranger and Joint Bookrunner,  THE OTHER LENDERS PARTY
HERETO,  J.P. MORGAN SECURITIES LLC,  as Joint Lead Arranger, Joint Bookrunner and Syndication Agent,  and
BARCLAYS BANK PLC,
MERRILL LYNCH, PIERCE, FENNER & SMITH INCORPORATED and  CREDIT SUISSE
--------------------------------------------------

=== Document 5 ===
Doc length: 1155082
Text length: 242130
F CREDIT




Exhibit 10.1 Unsecured line of credit
CREDIT AGREEMENTDated as of January 31, 2013amongACADIA REALTY LIMITED PARTNERSHIP,as the Borrower,andACADIA REALTY TRUSTandCERTAIN SUBSIDIARIES OFACADIA REALTY LIMITED PARTNERSHIPFROM TIME TO TIME PARTY HERETO,as GuarantorsBANK OF AMERICA, N.A.,as Administrative Agent, Swing Line Lender,L/C Issuer and as a Lender,PNC BANK, NATIONAL ASSOCIATIONandWELLS FARGO BANK, NATIONAL ASSOCIATION,as Co-Documentation AgentsandThe Other Lenders Party HeretoME
--------------------------------------------------

=== Document 6 ===
Doc length: 1109200
Text length: 269645
EX-10.2
3
a102loanagreement-bankofch.htm
ONE WILSHIRE BANK OF CHINA AGREEMENT




10.2 LoanAgreement-BankofChina_OneWilshireLoan
Exhibit 10.2LOAN AGREEMENTbetweenBANK OF CHINA, LOS ANGELES BRANCH(“Lender”)andHINES REIT ONE WILSHIRE LP(“Borrower”)14961843v.6TABLE OF CONTENTSPageArticle I DEFINITIONS; PRINCIPLES OF CONSTRUCTION11.1Definitions.

262.1Agreement to Lend and Borrow.    262.2Advance of Loan Proceeds.    262.3Single Disbursement to Borrower.    272.4Note, Security Instrument and Loan D
--------------------------------------------------

=== Document 7 ===
Doc length: 867842
Text length: 265981
2
v366863_ex10-1.htm
EXHIBIT 10.1







CREDIT AGREEMENT

Dated as of January 27, 2014
among

SAMSON OIL AND GAS USA, INC.,
as Borrower,

MUTUAL OF OMAHA BANK,
as Administrative Agent

and

L/C Issuer,

and

The Other Lenders Party Hereto









TABLE OF CONTENTS





Page





ARTICLE I. DEFINITIONS AND ACC

35

2.09.
Computation of Interest and Fees
35

2.10.
Evidence of Debt
35

2.11.
Payments Generally; Administrative Agent's Clawback
36

2.12.
Sharing of Payments
3
--------------------------------------------------

=== Document 8 ===
Doc length: 482694
Text length: 133328
Loan Number:  1008764

    TERM LOAN AGREEMENT  Dated as of January 22, 2013
by and among
TAU OPERATING PARTNERSHIP, L.P.,
                         as Borrower,  THE FINANCIAL INSTITUTI

D THEIR ASSIGNEES UNDER
SECTION 12.6.,

                                 as Lenders,
and  WELLS FARGO
BANK, NATIONAL ASSOCIATION,


            as Administrative Agent
  WELLS
--------------------------------------------------

=== Document 9 ===
Doc length: 618511
Text length: 153344
.3  Execution Version

$100,000,000
CREDIT AGREEMENT
among  SUNCOKE
ENERGY PARTNERS, L.P.,  HAVERHILL COKE COMPANY LLC,  MIDDLETOWN COKE COMPANY, LLC,  HAVERHILL COGENERATION COMPANY LLC,
MIDDLETOWN COGENERATION COMPANY LLC  and  CERTAIN OTHER SUBSIDIARIES OF SUNCOKE ENERGY PARTNERS, L.P.,
as joint and several Borrowers,  The Several Lenders from Time to Time Parties Hereto,  BARCLAYS BANK PLC,
 as Syndication Agent,  BANK OF AMERICA, N.A.,  CITIBANK, N.A.
and  THE ROYAL
BANK OF SCOTL
--------------------------------------------------

=== Document 10 ===
Doc length: 2411213
Text length: 413864
CREDIT AGREEMENT

Dated as of February 12, 2018

among

VICTORY CAPITAL HOLDINGS, INC., as Borrower,

THE FINANCIAL INSTITUTIONS PARTY HERETO, as Lenders,

ROYAL BANK OF CANADA, as Administrative Agent,

RBC CAPITAL MARKETS* and JPMORGAN CHASE BANK, N.A.,  as Joint Lead Arrangers and Joint Bookrunne

eeds; Sharing of Payments



92


Section 2.19.



Mitigation   Obligations; Replacement of Lenders



94


Section 2.20.



Illegality



95


Section 2.21.



Default
--------------------------------------------------

=== Document 11 ===
Doc length: 516597
Text length: 120787
ION COPY

U.S. $1,500,000,000

364-DAY CREDIT AGREEMENT

Dated as of February 16, 2018

Among

HONEYWELL INTERNATIONAL INC.,

as Borrower,

and

THE INITIAL LENDERS NAMED HEREIN,

as Initial Lenders,

and

JPMORGAN CHASE BANK, N.A.,

as Administrative Agent

and

GOLDMAN SACHS BANK USA,
as Syndication Agent

and

JPMORGAN CHASE BANK, N.A.
and
GOLDMAN SACHS BANK USA,

as Joint Lead Arrangers
and Co-Book Managers




TABLE OF CONTENTS








Page

ARTICLE I



6





--------------------------------------------------

=== Document 12 ===
Doc length: 511360
Text length: 174813
NS BOOTS
ALLIANCE, INC.,  THE LENDERS FROM TIME TO TIME PARTIES HERETO,
and  MIZUHO BANK, LTD.
 as Administrative Agent
and  MIZUHO BANK, LTD.,
 BANK OF AMERICA, N.A.,
HSBC SECURITIES (USA), INC.,
INTESA SANPAOLO S.P.A., NEW YORK BRANCH,
MUFG BANK, LTD.,
UNICREDIT BANK AG, NEW YORK BRANCH,
JPMORGAN CHASE BANK, N.A.,
U.S. BANK NATIONAL ASSOCIATION,
NATIONAL WESTMINSTER BANK PLC
and  THE TORONTO-DOMINION
BANK, NEW YORK BRANCH  as Co-Syndication Agents
MIZUHO BANK, LTD.,
MERRILL LYNCH,
--------------------------------------------------

=== Document 13 ===
Doc length: 901226
Text length: 178131
1.htm
EX-10.1


Exhibit 10.1






CREDIT AGREEMENT

dated as of January 29, 2019,

among

CVR ENERGY, INC.,
as Borrower,

JEFFERIES FINANCE LLC,
as Administrative Agent, Collateral Agent and Sole Lead Arranger,

and

THE LENDERS NAMED HEREIN
as Lenders

$105,000,000












TABLE OF CONTENTS








PAGE







Article I   DE

ions

42


Section 2.13

Taxes

44


Section 2.14

Mitigation Obligations;   Replacement of Lenders

48







Article
--------------------------------------------------

=== Document 14 ===
Doc length: 1360105
Text length: 193798
G S.A.,


as Borrower,


THE LENDERS PARTY HERETO


and


ANGELO, GORDON ENERGY SERVICER, LLC,


as Administrative Agent



























Table of Contents



























P


60





SECTION 2.13



Pro Rata Treatment

61





SECTION 2.14



Sharing of Payments by Lenders

61





SECTION 2.15



Payments

62





SECTION 2.16



Taxes

63





SECTION 2.17



Mitigation Obligations; Replacement of Lenders

65





SECTION
--------------------------------------------------

=== Document 15 ===
Doc length: 644033
Text length: 28073
114dex102.htm
EX-10.2

EX-10.2
Exhibit 10.2
LOAN AGREEMENT  Dated as
of February 1, 2018  Between
2477 DEERFIELD DRIVE, LLC,
as Borrower  and
UBS AG, BY AND THROUGH ITS BRANCH OFFICE AT
1285 AVENUE OF THE AMERICAS, NEW YORK, NEW YORK,
as Lender


 Management Account


49


Section 4.2

 Survival of Representations


50





ARTICLE V  BORROWER COVENANTS


50


Section 5.1

 Affirmative Covenants


50


5.1.1

 Existence; Compliance

v


LOAN AGREEMENT
THIS LOAN AGREE
--------------------------------------------------

=== Document 16 ===
Doc length: 802406
Text length: 178054
TANDARD
DIVERSIFIED OPPORTUNITIES INC.,

THE OTHER PERSONS PARTY HERETO THAT ARE

DESIGNATED AS BORROWERS,

THE FINANCIAL INSTITUTIONS PARTY HERETO,

as Term Lenders,

and

CRYSTAL FINANCIAL LLC,

as Term Agent

****************************************






TABLE OF CONTENTS



ARTICLE I. THE TERM LOAN
1

1.1
Amount of the Term Loan; Protective Overadvances
1

1.2
Evidence of Term Loan; Term Notes
3

1.3
Interest
4

1.4
Loan Accounts
4

1.5
Optional Prepayments of the Term
--------------------------------------------------

=== Document 17 ===
Doc length: 2048856
Text length: 297741
SIONU.S. $850,000,000 CREDIT AGREEMENTDated as of November 28, 2017amongEXGEN RENEWABLES IV, LLC,as Borrower,EXGEN RENEWABLES IV HOLDING, LLC,as Holding,THE LENDERS PARTY HERETO,WILMINGTON TRUST, NATIONAL ASSOCIATION, as Depositary Bank,MORGAN STANLEY SENIOR FUNDING, INC.,as Administrative Agent, and WILMINGTON TRUST, NATIONAL ASSOCIATION,as Collateral Agent_______________________________________________MORGAN STANLEY SENIOR FUNDING, INC.,as Sole Lead Arranger and Sole Lead Bookrunner,MORGAN STA
--------------------------------------------------

=== Document 18 ===
Doc length: 806307
Text length: 202545
Loan CUSIP Number:  25537JAK3

CREDIT AGREEMENT

Dated as of January 11, 2019

by and among

BLACK CREEK DIVERSIFIED PROPERTY OPERATING PARTNERSHIP LP,
a Delaware limited partnership,
as Borrower,

THE FINANCIAL INSTITUTIONS PARTY HERETO
AND THEIR ASSIGNEES UNDER SECTION 13.5.,
as Lenders,

and

WELLS FARGO BANK, NATIONAL ASSOCIATION,
as Administrative Agent



WELLS FARGO SECURITIES, LLC,

and

REGIONS CAPITAL MARKETS,
as Joint Lead Arrangers and Bookrunners,

REGIONS BANK,
as Sy
--------------------------------------------------

=== Document 19 ===
Doc length: 1455858
Text length: 306596
Exhibit
EXHIBIT 10.28(e)Execution VersionCREDIT AGREEMENT  dated as of January 11, 2019  among  CASEY’S GENERAL STORES, INC., as Borrower,  The Lenders Party Hereto, and ROYAL BANK OF CANADA, as Administrative Agent, ___________________________  RBC CAPITAL MARKETSas Lead Arranger and Bookrunner   TABLE OF CONTENTSPageARTICLE I  DefinitionsSECTION 1.01.    Defined Terms    1SECTION 1.02.    Cl

N 2.02.    Loans and Borrowings    29SECTION 2.03.    Requests for Borrowings    30SECTION 2.04.    Sw
--------------------------------------------------

=== Document 20 ===
Doc length: 982441
Text length: 143780
EX-10.34
4
sigi-ex103412312019xq4.htm
EXHIBIT 10.34




Exhibit

Exhibit 10.34CREDIT AGREEMENT amongSELECTIVE INSURANCE GROUP, INC., as Borrower,THE LENDERS NAMED HEREIN andBANK OF MONTREAL, CHICAGO BRANCH, as Administrative Agent$50,000,000 Revolving Credit FacilityBMO CAPITAL MARKETS CORP., Sole Lead Arranger and Sole Lead BookrunnerDated as of December 20, 2019TABLE OF CONTENTS

ances; Illegality; etc 32Section 2.17 Taxes38Section 2.18 Compensation43Section 2.19 R
--------------------------------------------------

=== Document 21 ===
Doc length: 2314363
Text length: 486505
ex101_6.htm


Exhibit 10.1

EXECUTION VERSION
CREDIT AGREEMENT
Dated as of February 8, 2021
among
LD LOWER HOLDINGS, INC. as Borrower,
LD TOPCO, INC.
as Holdings Topco,
WILMINGTON TRUST, NATIONAL ASSOCIATION,as the Administrative Agent and Collateral Agent,
and
The Lenders and L/C Issuers Party Hereto




TABLE OF CONTENTS
Page
ARTICLE I. Definitions and Accounting Terms1






Sec

o Forma Calculations107








Section 1.11.

Calculation of Baskets107








Section 1.12.

Administ
--------------------------------------------------

=== Document 22 ===
Doc length: 1413380
Text length: 225584
EX-10.1
2
ois20210210_ex101.htm
EX-10.1




DocumentEXHIBIT 10.1CREDIT AGREEMENTby and amongWELLS FARGO BANK, NATIONAL ASSOCIATION,as Agent,WELLS FARGO BANK, NATIONAL ASSOCIATION, BANK OF AMERICA, N.A., andJPMORGAN CHASE BANK, N.A.,as Joint Lead Arrangers,WELLS FARGO BANK, NATIONAL ASSOCIATION, BANK OF AMERICA, N.A., andJPMORGAN CHASE BANK, N.A.,as Joint Book Runners,THE LENDERS THAT ARE PARTIES HERETOas the Lenders, andOIL STATES INTERNATIONAL, INC.,as BorrowerDated as of February 10, 2021TABLE
--------------------------------------------------

=== Document 23 ===
Doc length: 960917
Text length: 257761
sed.  Exhibit 10.1
EXECUTION VERSION

CREDIT AGREEMENT  Dated as
of January 24, 2022  among
SUNRUN INC.,  as the Borrower,
 THE SUBSIDIARIES OF THE BORROWER PARTY HERETO,
as the Guarantors,  KEYBANK
NATIONAL ASSOCIATION,  as Administrative Agent,
SILICON VALLEY BANK,  as
Collateral Agent  THE LENDERS PARTY HERETO
and  KEYBANC CAPITAL MARKETS
INC.,  as Coordinating Lead Arranger
MUFG BANK, LTD.,  as Joint Lead
Arranger  KEYBANC CAPITAL MARKETS INC. and
MUFG BANK, LTD.,  as Joint
Book
--------------------------------------------------

=== Document 24 ===
Doc length: 870972
Text length: 122924
EMENTDATED AS OF NOVEMBER 27, 2017BY AND AMONGCOLUMBIA PROPERTY TRUST OPERATING PARTNERSHIP, L.P.AS BORROWER,JPMORGAN CHASE BANK, N.A.,AS JOINT LEAD ARRANGER AND SOLE BOOKRUNNER,PNC CAPITAL MARKETS LLC, REGIONS CAPITAL MARKETS,SUNTRUST ROBINSON HUMPHREY, INC., U.S. BANK NATIONAL ASSOCIATION AND WELLS FARGO SECURITIES LLC,AS JOINT LEAD ARRANGERS,JPMORGAN CHASE BANK, N.A.,AS ADMINISTRATIVE AGENT,PNC BANK, NATIONAL ASSOCIATION, REGIONS BANK, SUNTRUST BANK,U.S. BANK NATIONAL ASSOCIATION AND WELLS FA
--------------------------------------------------

=== Document 25 ===
Doc length: 743293
Text length: 208265
HIBIT 10.1


Exhibit 10.1

Execution Version




CREDIT AND GUARANTY AGREEMENT

by and among

HUNT COMPANIES FINANCE TRUST, INC.

as Borrower,

FIVE OAKS ACQUISITION CORP. AND HUNT CMT
EQUITY, LLC

as Guarantors,

THE LENDERS PARTIES HERETO FROM TIME TO
TIME

as the Lenders,

CORTLAND CAPITAL MARKET SERVICES LLC,

together with its successors and assigns

as the Administrative Agent

and

CORTLAND CAPITAL MARKET SERVICES LLC,

together with its successors and assigns

as the Co
--------------------------------------------------

=== Document 26 ===
Doc length: 762869
Text length: 127915
AN AGREEMENT





Exhibit 10.1








$8,000,000,000


TERM LOAN CREDIT AGREEMENT




Among




BRISTOL-MYERS SQUIBB COMPANY,


THE LENDERS NAMED HEREIN,


BARCLAYS BANK PLC, CREDIT SUISSE LOAN FUNDING LLC, MIZUHO BANK, LTD. and WELLS FARGO BANK, NATIONAL ASSOCIATION,
as Documentation Agents,


MUFG BANK, LTD.,
as Syndication Agent,


MORGAN STANLEY SENIOR FUNDING, INC.,
as Administrative Agent.


Dated as of January 18, 2019






MORGAN STANLEY SENIOR FUNDING, INC., MUFG BANK, LTD., BARC
--------------------------------------------------

=== Document 27 ===
Doc length: 946612
Text length: 91148
ex102_37.htm


Exhibit 10.2
EXECUTION VERSION
CREDIT AGREEMENT
dated as of
January 22, 2019
between
GASTAR MIDCO HOLDINGS LLC, as Borrower,

and
AF V ENERGY I HOLDINGS, L.P.,as Lender





TABLE OF CONTENTS
Page




Article I. Definitions

1








Section 1.01

Defined Terms1


Section 3.22

No Foreign Operations34








Section 3.23

[Reserved]34








Section 3.24

Borrower as Holding Company34






Article IV. Conditions to Effectiveness and Borrowings

34








Se

stme
--------------------------------------------------

=== Document 28 ===
Doc length: 780140
Text length: 227248
0.2



Exhibit 10.2


Execution Version

LOAN AGREEMENT

Dated as of February 6, 2020

among

COLLEGIUM PHARMACEUTICAL, INC.

(as Borrower),

THE GUARANTORS PARTY HERETO

(as additional Credit Parties),

BIOPHARMA CREDIT PLC

(as Collateral Agent and
a Lender),

and

BIOPHARMA CREDIT INVESTMENTS V (MASTER)
LP

(as a Lender)







TABLE OF CONTENTS




Page




1.     ACCOUNTING
    AND OTHER TERMS
1

2.     LOAN

ding, Etc.
5

2.7.       Additional
    Consideration
7

2.8
--------------------------------------------------

=== Document 29 ===
Doc length: 1716032
Text length: 300406
EXECUTION VERSION











CREDIT AGREEMENT

dated as of

February 6, 2020

among

PAYCHEX ADVANCE LLC,as Borrower

PAYCHEX, INC.,as Parent

The Lenders Party HeretoPNC BANK, NATIONAL ASSOCIATION,as Administrative Agent





﻿







﻿




﻿






TABLE OF CONTENTS


Page






﻿









﻿ARTICLE I De

a Treatment; Sharing of Setoffs

53





﻿SECTION 2.19. Mitigation Obligations; Replacement of Lenders

54





﻿SECTION 2.20. [Intentionally Omitted]

5
--------------------------------------------------

=== Document 30 ===
Doc length: 650116
Text length: 157280
Senior Unsecured Revolving Credit Facility  CREDIT AGREEMENT  dated as of
January 28, 2013  among  Quanex Building Products Corporation,
the Guarantors party hereto,  the Lenders party hereto,  WELLS FARGO BANK, NATIONAL ASSOCIATION,
 as Administrative Agent  and  WELLS FARGO SECURITIES, LLC,
as Lead Arranger and Syndication Agent



TABLE OF CONTENTS











Page


 ARTICLE I Definitions


1


 SECTION 1.01

02 Loans and Borrowings


23


 SECTION 2.03 Requests for
--------------------------------------------------

=== Document 31 ===
Doc length: 918594
Text length: 222149
d CUSIP Number: 92827NAA5
364-DAY REVOLVING CREDIT AGREEMENT  DATED AS OF JANUARY 31, 2013  AMONG
VISA INC., VISA INTERNATIONAL SERVICE ASSOCIATION,  AND VISA U.S.A. INC.,  AS BORROWERS,
THE LENDERS,  AND
 BANK OF AMERICA, N.A.,  AS ADMINISTRATIVE AGENT  JPMORGAN CHASE BANK, N.A.,
AS SYNDICATION AGENT
CITIBANK, N.A.,  STANDARD
CHARTERED BANK,  THE BANK OF TOKYO-MITSUBISHI UFJ, LTD.,
U.S. BANK NATIONAL ASSOCIATION,
WELLS FARGO BANK, NATIONAL ASSOCIATION,  BANK OF CHINA, LOS ANGELES BRANCH
--------------------------------------------------

=== Document 32 ===
Doc length: 1527252
Text length: 425185
101.htm
EX-10.1

EX-10.1
Exhibit 10.1

  CREDIT AGREEMENT
Dated as of January 23, 2014  among  CHC GROUP LTD., as the Parent Guarantor
6922767 HOLDING S.À R.L., as the Company,  CHC HELICOPTER HOLDING S.À R.L., as Holdco,  CHC HELICOPTER S.A.,
 as Initial Borrower,  THE LENDERS PARTY HERETO,  HSBC BANK PLC,
as Administrative Agent  HSBC CORPORATE TRUSTEE COMPANY (UK) LIMITED,  as Collateral Agent,
HSBC BANK CANADA,
J.P. MORGAN SECURITIES LLC,  BARCLAYS BANK PLC,  RBC CAPITAL MARKETS* an
--------------------------------------------------

=== Document 33 ===
Doc length: 642208
Text length: 202741
ent
Exhibit 10.1
EXECUTION VERSION

CREDIT AGREEMENT  dated as of
 January 30, 2014,
among  PLY GEM HOLDINGS, INC.,
 PLY GEM INDUSTRIES, INC.,
THE LENDERS PARTY HERETO,  and
 CREDIT SUISSE AG,  as
Administrative Agent and Collateral Agent
  CREDIT SUISSE
SECURITIES (USA) LLC,  UBS SECURITIES LLC,
J.P. MORGAN SECURITIES LLC, and
GOLDMAN SACHS BANK USA,  as Joint
Lead Arrangers and Joint Bookrunners,  RBC CAPITAL MARKETS, LLC,
as Joint Lead Arranger,  J.P.
MORGAN SECURITIES LLC,  as
--------------------------------------------------

=== Document 34 ===
Doc length: 644513
Text length: 150153
1

EXECUTION COPY

U.S. $50,000,000

TERM LOAN CREDIT AGREEMENT

dated as of January 31, 2014

MICHIGAN ELECTRIC TRANSMISSION COMPANY, LLC
as the Borrower,

VARIOUS FINANCIAL INSTITUTIONS AND OTHER PERSONS
FROM TIME TO TIME PARTIES HERETO,
as the Lenders,

GOLDMAN SACHS BANK USA, as the Administrative Agent,

and

GOLDMAN SACHS BANK USA, as Sole Lead Arranger and Sole Bookrunner








KeyboardInterrupt:

In [35]:
import json
import re
from bs4 import BeautifulSoup

def extract_clean_text_snippets(data, padding=100):
    snippets = {}
    
    for i in range(len(data)):
        snippets[data[i]['id']] = []
        
        raw_html = data[i]["data"]["html"]
        annotations = data[i]["annotations"][0]["result"]
    
        # Step 1: Clean HTML to plain text
        soup = BeautifulSoup(raw_html, 'html.parser')
        plain_text = soup.get_text()
    
        # Step 2: Extract context snippets from clean text
        for ann in annotations:
            value = ann.get("value", {})
            if "globalOffsets" not in value or "text" not in value:
                continue
    
            label = value.get("hypertextlabels", [])
            entity_text = value["text"]
            start = value["globalOffsets"]["start"]
            end = value["globalOffsets"]["end"]
    
            context_start = max(0, start - padding)
            context_end = min(len(plain_text), end + padding)
            snippet = plain_text[context_start:context_end]
    
            snippets[data[i]['id']].append({
                "label": label,
                "text": entity_text,
                "context_snippet": snippet
            })

    return snippets

snippets = extract_clean_text_snippets(merged_, padding=100)

for doc_id, s_list in snippets.items():
    print(f'\nDoc ID: {doc_id}')
    for s in s_list[:5]:
        print(f"\nLabel: {s['label']}")
        print(f"Text: {s['text']}")
        print(f"Context Snippet:\n{s['context_snippet']}\n{'-'*40}")

Doc ID: 1

Label: ['Organization Name']
Text: FRANKLIN RESOURCES, INC.
Context Snippet:
k Constant            Name:  Mark ConstantTitle:  Vice President and Treasurer[Signature Page to Credit Agreement]BANK OF AMERICA, N.A.,as Administrative AgentBy:  /s/    Alexandra M. Knights            Name:  Alexandra M. K
----------------------------------------

Label: ['Person Name']
Text: Mark Constant
Context Snippet:
reasurer[Signature Page to Credit Agreement]BANK OF AMERICA, N.A.,as Administrative AgentBy:  /s/    Alexandra M. Knights            Name:  Alexandra M. KnightsTitle:    Authorized Signatory[Signature Page to Cred
----------------------------------------

Label: ['Person Position']
Text: Vice President
Context Snippet:
ge to Credit Agreement]BANK OF AMERICA, N.A.,as Administrative AgentBy:  /s/    Alexandra M. Knights            Name:  Alexandra M. KnightsTitle:    Authorized Signatory[Signature Page to Credit Agreement]BANK OF A
----------------------------------------

Label: ['Person Position']
Text: Treasurer
Context Snippet:
ent]BANK OF AMERICA, N.A.,as Administrative AgentBy:  /s/    Alexandra M. Knights            Name:  Alexandra M. KnightsTitle:    Authorized Signatory[Signature Page to Credit Agreement]BANK OF AMERICA, N.A.,
----------------------------------------

Label: ['Organization Name']
Text: BANK OF AMERICA, N.A.
Context Snippet:
By:  /s/    Alexandra M. Knights            Name:  Alexandra M. KnightsTitle:    Authorized Signatory[Signature Page to Credit Agreement]BANK OF AMERICA, N.A., as a LenderBy:  /s/    Alexandra M. Knights            Name:
----------------------------------------

Doc ID: 2

Label: ['Organization Name']
Text: DICKS SPORTING GOODS, INC.
Context Snippet:
WHEREOF, the parties hereto have executed this Agreement as of the date first
written above.




DICKS SPORTING GOODS, INC.,

as the Borrower



/s/ Navdeep Gupta

Name: Navdeep Gupta

Title: Executive Vice President and Ch
----------------------------------------

Label: ['Organization Role']
Text: Borrower
Context Snippet:
uted this Agreement as of the date first
written above.




DICKS SPORTING GOODS, INC.,

as the Borrower



/s/ Navdeep Gupta

Name: Navdeep Gupta

Title: Executive Vice President and Chief Financial Offi
----------------------------------------

Label: ['Person Name']
Text: Navdeep Gupta
Context Snippet:
rst
written above.




DICKS SPORTING GOODS, INC.,

as the Borrower



/s/ Navdeep Gupta

Name: Navdeep Gupta

Title: Executive Vice President and Chief Financial Officer
 [Signature Page to Credit Agreement]
----------------------------------------

Label: ['Person Position']
Text: Executive Vice President
Context Snippet:




DICKS SPORTING GOODS, INC.,

as the Borrower



/s/ Navdeep Gupta

Name: Navdeep Gupta

Title: Executive Vice President and Chief Financial Officer
 [Signature Page to Credit Agreement]














ADMINISTRATIVE AGE
----------------------------------------

Label: ['Person Position']
Text: Chief Financial Officer
Context Snippet:
C.,

as the Borrower



/s/ Navdeep Gupta

Name: Navdeep Gupta

Title: Executive Vice President and Chief Financial Officer
 [Signature Page to Credit Agreement]














ADMINISTRATIVE AGENT:



    WELLS FARGO BAN
----------------------------------------

Doc ID: 3

Label: ['Organization Role']
Text: BORROWER
Context Snippet:
presentatives thereunto duly authorized, as of the
date first above written.




BORROWERS:





SUMMIT JV MR 2, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christophe
----------------------------------------

Label: ['Organization Name']
Text: SUMMIT JV MR 2, LLC
Context Snippet:
eunto duly authorized, as of the
date first above written.




BORROWERS:





SUMMIT JV MR 2, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secreta
----------------------------------------

Label: ['Person Name']
Text: Christopher Eng
Context Snippet:
 LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT JV MR 3, LLC,
a Delaware limited liability company



By:/s/ Christopher En
----------------------------------------

Label: ['Person Position']
Text: Secretary
Context Snippet:
ty company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT JV MR 3, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher
----------------------------------------

Label: ['Organization Name']
Text: 	SUMMIT JV MR 3, LLC
Context Snippet:
:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT JV MR 3, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secreta
----------------------------------------

Doc ID: 4

Label: ['Organization Name']
Text: BRIGHT HORIZONS FAMILY SOLUTIONS LLC
Context Snippet:
ave caused this Agreement to be duly executed
as of the date first above written.






 BRIGHT HORIZONS FAMILY SOLUTIONS LLC, as Borrower




 By:

/s/ David Lissy



Name:  David Lissy



Title:    Chief Executive Officer





----------------------------------------

Label: ['Organization Role']
Text: Borrower
Context Snippet:
uted
as of the date first above written.






 BRIGHT HORIZONS FAMILY SOLUTIONS LLC, as Borrower




 By:

/s/ David Lissy



Name:  David Lissy



Title:    Chief Executive Officer











 BRIG
----------------------------------------

Label: ['Person Name']
Text: David Lissy
Context Snippet:



 BRIGHT HORIZONS FAMILY SOLUTIONS LLC, as Borrower




 By:

/s/ David Lissy



Name:  David Lissy



Title:    Chief Executive Officer











 BRIGHT HORIZONS CAPITAL CORP., as Holdings




 By:


----------------------------------------

Label: ['Organization Name']
Text: BRIGHT HORIZONS CAPITAL CORP.,
Context Snippet:
/s/ David Lissy



Name:  David Lissy



Title:    Chief Executive Officer











 BRIGHT HORIZONS CAPITAL CORP., as Holdings




 By:

/s/ David Lissy



Name:  David Lissy



Title:    Chief Executive Officer





----------------------------------------

Label: ['Organization Role']
Text: Holdings
Context Snippet:
issy



Title:    Chief Executive Officer











 BRIGHT HORIZONS CAPITAL CORP., as Holdings




 By:

/s/ David Lissy



Name:  David Lissy



Title:    Chief Executive Officer




   [Credit Agr
----------------------------------------

Doc ID: 5

Label: ['Organization Name']
Text: ACADIA REALTY LIMITED PARTNERSHIP
Context Snippet:
EDIT




Exhibit 10.1 Unsecured line of credit
CREDIT AGREEMENTDated as of January 31, 2013amongACADIA REALTY LIMITED PARTNERSHIP,as the Borrower,andACADIA REALTY TRUSTandCERTAIN SUBSIDIARIES OFACADIA REALTY LIMITED PARTNERSHIPFROM T
----------------------------------------

Label: ['Organization Role']
Text: Borrower
Context Snippet:
redit
CREDIT AGREEMENTDated as of January 31, 2013amongACADIA REALTY LIMITED PARTNERSHIP,as the Borrower,andACADIA REALTY TRUSTandCERTAIN SUBSIDIARIES OFACADIA REALTY LIMITED PARTNERSHIPFROM TIME TO TIME PART
----------------------------------------

Label: ['Organization Name']
Text: ACADIA REALTY TRUST
Context Snippet:
 AGREEMENTDated as of January 31, 2013amongACADIA REALTY LIMITED PARTNERSHIP,as the Borrower,andACADIA REALTY TRUSTandCERTAIN SUBSIDIARIES OFACADIA REALTY LIMITED PARTNERSHIPFROM TIME TO TIME PARTY HERETO,as GuarantorsB
----------------------------------------

Label: ['Organization Sub-Role']
Text: SUBSIDIARIES
Context Snippet:
31, 2013amongACADIA REALTY LIMITED PARTNERSHIP,as the Borrower,andACADIA REALTY TRUSTandCERTAIN SUBSIDIARIES OFACADIA REALTY LIMITED PARTNERSHIPFROM TIME TO TIME PARTY HERETO,as GuarantorsBANK OF AMERICA, N.A.,as
----------------------------------------

Label: ['Organization Name']
Text: ACADIA REALTY LIMITED PARTNERSHIP
Context Snippet:
ADIA REALTY LIMITED PARTNERSHIP,as the Borrower,andACADIA REALTY TRUSTandCERTAIN SUBSIDIARIES OFACADIA REALTY LIMITED PARTNERSHIPFROM TIME TO TIME PARTY HERETO,as GuarantorsBANK OF AMERICA, N.A.,as Administrative Agent, Swing Line Le
----------------------------------------

Doc ID: 6

Label: ['Organization Name']
Text: BANK OF CHINA
Context Snippet:
NA AGREEMENT




10.2 LoanAgreement-BankofChina_OneWilshireLoan
Exhibit 10.2LOAN AGREEMENTbetweenBANK OF CHINA, LOS ANGELES BRANCH(“Lender”)andHINES REIT ONE WILSHIRE LP(“Borrower”)14961843v.6TABLE OF CONTENTSPage
----------------------------------------

Label: ['Location']
Text: LOS ANGELES
Context Snippet:


10.2 LoanAgreement-BankofChina_OneWilshireLoan
Exhibit 10.2LOAN AGREEMENTbetweenBANK OF CHINA, LOS ANGELES BRANCH(“Lender”)andHINES REIT ONE WILSHIRE LP(“Borrower”)14961843v.6TABLE OF CONTENTSPageArticle I DEF
----------------------------------------

Label: ['Location Type']
Text: BRANCH
Context Snippet:
greement-BankofChina_OneWilshireLoan
Exhibit 10.2LOAN AGREEMENTbetweenBANK OF CHINA, LOS ANGELES BRANCH(“Lender”)andHINES REIT ONE WILSHIRE LP(“Borrower”)14961843v.6TABLE OF CONTENTSPageArticle I DEFINITION
----------------------------------------

Label: ['Organization Role']
Text: Lender
Context Snippet:
-BankofChina_OneWilshireLoan
Exhibit 10.2LOAN AGREEMENTbetweenBANK OF CHINA, LOS ANGELES BRANCH(“Lender”)andHINES REIT ONE WILSHIRE LP(“Borrower”)14961843v.6TABLE OF CONTENTSPageArticle I DEFINITIONS; PRINC
----------------------------------------

Label: ['Organization Name']
Text: HINES REIT ONE WILSHIRE LP
Context Snippet:
a_OneWilshireLoan
Exhibit 10.2LOAN AGREEMENTbetweenBANK OF CHINA, LOS ANGELES BRANCH(“Lender”)andHINES REIT ONE WILSHIRE LP(“Borrower”)14961843v.6TABLE OF CONTENTSPageArticle I DEFINITIONS; PRINCIPLES OF CONSTRUCTION11.1Defini
----------------------------------------

Doc ID: 7

Label: ['Organization Name']
Text: SAMSON OIL AND GAS USA, INC
Context Snippet:
2
v366863_ex10-1.htm
EXHIBIT 10.1







CREDIT AGREEMENT

Dated as of January 27, 2014
among

SAMSON OIL AND GAS USA, INC.,
as Borrower,

MUTUAL OF OMAHA BANK,
as Administrative Agent

and

L/C Issuer,

and

The Othe
----------------------------------------

Label: ['Organization Role']
Text: Borrower
Context Snippet:








CREDIT AGREEMENT

Dated as of January 27, 2014
among

SAMSON OIL AND GAS USA, INC.,
as Borrower,

MUTUAL OF OMAHA BANK,
as Administrative Agent

and

L/C Issuer,

and

The Other Lenders Part
----------------------------------------

Label: ['Organization Name']
Text: MUTUAL OF OMAHA BANK
Context Snippet:
REDIT AGREEMENT

Dated as of January 27, 2014
among

SAMSON OIL AND GAS USA, INC.,
as Borrower,

MUTUAL OF OMAHA BANK,
as Administrative Agent

and

L/C Issuer,

and

The Other Lenders Party Hereto









----------------------------------------

Label: ['Organization Role']
Text: Administrative Agent
Context Snippet:
s of January 27, 2014
among

SAMSON OIL AND GAS USA, INC.,
as Borrower,

MUTUAL OF OMAHA BANK,
as Administrative Agent

and

L/C Issuer,

and

The Other Lenders Party Hereto









TABLE OF CONTENTS





----------------------------------------

Label: ['Organization Role']
Text: L/C Issuer
Context Snippet:

SAMSON OIL AND GAS USA, INC.,
as Borrower,

MUTUAL OF OMAHA BANK,
as Administrative Agent

and

L/C Issuer,

and

The Other Lenders Party Hereto









TABLE OF CONTENTS





Page





ARTI
----------------------------------------

Doc ID: 8

Label: ['Location']
Text: 608 Second Avenue South, 11th Floor\nMinneapolis, MN 55402
Context Snippet:
2111

  - 59 -


If to the Administrative Agent:







Wells Fargo Bank, National Association

608 Second Avenue South, 11th Floor

Minneapolis, MN 55402

Attn:  Mark Nardi, Loan No. 1008764

Telecopier:

 (612) 667-5381

Telephone:

 (612) 316-0114

----------------------------------------

Label: ['Location']
Text: 401 B Street, Suite 1100\nSan Diego, California 92101
Context Snippet:
1

Telephone:

 (612) 316-0114
 with a copy to:







Wells Fargo Bank, National Association

401 B Street, Suite 1100

San Diego, California 92101

Attn:  Dale Northup

Telecopier:

 (619) 699-3105

Telephone:

 (619) 699-3025
 If to any Lende
----------------------------------------

Label: ['Organization Name']
Text: WELLS FARGO BANK, NATIONAL ASSOCIATION
Context Snippet:
ES UNDER
SECTION 12.6.,

                                 as Lenders,
and  WELLS FARGO
BANK, NATIONAL ASSOCIATION,


            as Administrative A
----------------------------------------

Label: ['Organization Name']
Text: WELLS FARGO SECURITIES, LLC
Context Snippet:


            as Administrative Agent
  WELLS FARGO
SECURITIES, LLC  and  MERRILL LYNCH, PIERCE, FENNER & SMITH INCORPORATED,


----------------------------------------

Label: ['Organization Name']
Text: MERRILL LYNCH, PIERCE, FENNER & SMITH INCORPORATED
Context Snippet:

            as Administrative Agent
  WELLS FARGO
SECURITIES, LLC  and  MERRILL LYNCH, PIERCE, FENNER & SMITH INCORPORATED,


          as Joint Lead Arrange
----------------------------------------

Doc ID: 9

Label: ['Organization Role']
Text: Lender
Context Snippet:
 Walton



Title: Authorized Signatory

  115










BRANCH BANKING AND TRUST COMPANY, as a Lender




By:

 /s/ Eric Searls



Name: Eric Searls



Title: Senior Vice President

  116



Credit Agre
----------------------------------------

Label: ['Person Name']
Text: Eric Searls
Context Snippet:
15










BRANCH BANKING AND TRUST COMPANY, as a Lender




By:

 /s/ Eric Searls



Name: Eric Searls



Title: Senior Vice President

  116



Credit Agreement Schedules  SCHEDULES:






1.1A

Revo
----------------------------------------

Label: ['Person Position']
Text: Senior Vice President
Context Snippet:
KING AND TRUST COMPANY, as a Lender




By:

 /s/ Eric Searls



Name: Eric Searls



Title: Senior Vice President

  116



Credit Agreement Schedules  SCHEDULES:






1.1A

Revolving Commitments

1.1B

Mortga
----------------------------------------

Label: ['Organization Name']
Text: BRANCH BANKING AND TRUST COMPANY
Context Snippet:


By:

 /s/ Mark Walton



Name: Mark Walton



Title: Authorized Signatory

  115










BRANCH BANKING AND TRUST COMPANY, as a Lender




By:

 /s/ Eric Searls



Name: Eric Searls



Title: Senior Vice President

  116


----------------------------------------

Label: ['Organization Role']
Text: Lender
Context Snippet:
Brian D. Williams



Title: Authorised Signatory

  114










GOLDMAN SACHS BANK USA, as a Lender




By:

 /s/ Mark Walton



Name: Mark Walton



Title: Authorized Signatory

  115










BRANC
----------------------------------------

Doc ID: 10

Label: ['Person Name']
Text: 	\nSusan Khokher
Context Snippet:










ROYAL BANK OF CANADA,




as Issuing Bank and a Lender














By:

/s/ Alex Figueroa






Name:

Alex Figueroa






Title:

Authorized Signatory

Signatu
----------------------------------------

Label: ['Person Name']
Text: Alex Figueroa
Context Snippet:













JPMorgan Chase Bank, N.A.,




as a Lender














By:

/s/ Kenise Henry Larmond




Name:

Kenise Henry Larmond




Title:

Vice President

Signature Page
----------------------------------------

Label: ['Person Name']
Text: 	\nKenise Henry Larmond
Context Snippet:










MORGAN STANLEY SENIOR   FUNDING, INC.,




as a Lender














By:

/s/ Michael King




Name:

Michael King




Title:

Vice President

Signature Page to Victory Cred
----------------------------------------

Label: ['Person Name']
Text: 	\nMichael King
Context Snippet:


BANK OF AMERICA, N.A.




as a Lender














By:

/s/ Rodney Beeks




Name:

Rodney Beeks




Title:

Associate

Signature Page to Victory Credit Agreement









----------------------------------------

Label: ['Person Name']
Text: 	\nRodney Beeks
Context Snippet:
YBANK NATIONAL ASSOCIATION




as a Lender














By:

/s/ Shane M. Leary




Name:

Shane M. Leary




Title:

Vice President






Signature Page to Victory Credit Agr
----------------------------------------

Doc ID: 11

Label: ['Organization Name']
Text: 	GOLDMAN SACHS BANK USA
Context Snippet:
 Gene Riego de Dios


Title: Executive Director


[Honeywell Credit Agreement]







GOLDMAN SACHS BANK USA, as an Initial Lender





By:
/s/ Robert Ehudin



Name: Robert Ehudin


Title: Authorized Signatory

----------------------------------------

Label: ['Organization Name']
Text: BANK OF AMERICA, N.A.
Context Snippet:


By:
/s/ Robert Ehudin



Name: Robert Ehudin


Title: Authorized Signatory





BANK OF AMERICA, N.A., as an Initial Lender





By:
/s/ Mukesh Singh



Name: Mukesh Singh


Title: Director





BARCLAY
----------------------------------------

Label: ['Organization Name']
Text: BARCLAYS BANK PLC
Context Snippet:
al Lender





By:
/s/ Mukesh Singh



Name: Mukesh Singh


Title: Director





BARCLAYS BANK PLC, as an Initial Lender





By:
/s/ Craig Malloy



Name: Craig Malloy


Title: Director





CITIBAN
----------------------------------------

Label: ['Organization Name']
Text: 	CITIBANK, N.A.
Context Snippet:
al Lender





By:
/s/ Craig Malloy



Name: Craig Malloy


Title: Director





CITIBANK, N.A., as an Initial Lender





By:
/s/ Carolyn Kee



Name: Carolyn Kee


Title: Vice President





DEU
----------------------------------------

Label: ['Organization Name']
Text: 	DEUTSCHE BANK AG NEW YORK BRANCH,
Context Snippet:
ender





By:
/s/ Carolyn Kee



Name: Carolyn Kee


Title: Vice President





DEUTSCHE BANK AG NEW YORK BRANCH, as an Initial Lender





By:
/s/ Ming K. Chu



Name: Ming K. Chu


Title: Director





By:
/s/ Vi
----------------------------------------

Doc ID: 12

Label: ['Organization Name']
Text: \nWALGREENS BOOTS ALLIANCE, INC.
Context Snippet:
REOF, the parties hereto have executed this Agreement as of the date first
written above.






 WALGREENS BOOTS ALLIANCE, INC.,
as the Borrower




By:

/s/ Aidan Clare

Name: Aidan Clare

Title: Senior Vice President and Glo
----------------------------------------

Label: ['Organization Name']
Text: MIZUHO BANK, LTD.,
Context Snippet:
ident, Global Treasury

  [Signature
Page to Credit Agreement]




ADMINISTRATIVE AGENT:







 MIZUHO BANK, LTD., as the
Administrative Agent




By:

/s/ Tracy Rahn

Name: Tracy Rahn

Title: Authorized Signatory
----------------------------------------

Label: ['Organization Name']
Text: MIZUHO BANK, LTD.,
Context Snippet:
e Agent




By:

/s/ Tracy Rahn

Name: Tracy Rahn

Title: Authorized Signatory
 LENDERS:






 MIZUHO BANK, LTD., as a
Lender




By:

/s/ Tracy Rahn

Name: Tracy Rahn

Title: Authorized Signatory

  [Signature
P
----------------------------------------

Label: ['Organization Name']
Text: BANK OF AMERICA, N.A.,
Context Snippet:

Name: Tracy Rahn

Title: Authorized Signatory

  [Signature
Page to Credit Agreement]











 BANK OF AMERICA, N.A., as a
Lender




By:

/s/ J. Casey Cosgrove

Name: J. Casey Cosgrove

Title: Director

  [Signature
----------------------------------------

Label: ['Organization Name']
Text: \nHSBC BANK USA, N.A.,
Context Snippet:
rove

Name: J. Casey Cosgrove

Title: Director

  [Signature
Page to Credit Agreement]











 HSBC BANK USA, N.A., as a
Lender




By:

/s/ Thomas Foley

Name: Thomas Foley

Title: Managing Director

  [Signature

----------------------------------------

Doc ID: 13

Label: ['Organization Name']
Text: CVR ENERGY, INC
Context Snippet:
ainder of this page intentionally left blank. Signature page follows.]

104











CVR   ENERGY, INC.,   a Delaware Corporation














By:

/s/   Tracy D. Jackson




Name:

Tracy
----------------------------------------

Label: ['Organization Name']
Text: 	\nJEFFERIES FINANCE LLC
Context Snippet:
  Chief Financial Officer






[Signature Page to Credit Agreement]












JEFFERIES   FINANCE LLC, as   Administrative Agent, Collateral Agent, and a Lender














By:

/s/   John Koeh

In [36]:
for doc_id, s_list in snippets.items():
    print(f'{doc_id}: {len(s_list)}')

1: 29
2: 77
3: 335
4: 71
5: 56
6: 25
7: 25
8: 21
9: 106
10: 33
11: 47
12: 65
13: 16
14: 40
15: 21
16: 30
17: 39
18: 40
19: 58
20: 15
21: 71
22: 44
23: 72
24: 59
25: 53
26: 179
27: 29
28: 85
29: 276
30: 63
31: 157
32: 237
33: 47
34: 47
35: 242
36: 23
37: 459
38: 132
39: 61
40: 55
41: 66
42: 94
43: 18
44: 35
45: 20
46: 35
47: 70
48: 20
49: 66
50: 62
51: 35
52: 74
53: 27
54: 17
55: 31
56: 54
57: 156
58: 35
59: 76
60: 81
61: 52
62: 27
63: 23
64: 42
65: 85
66: 111
67: 57
68: 80
69: 91
70: 65
71: 18
72: 30
73: 68
74: 46
75: 22
76: 36
77: 61
78: 12
79: 110
80: 59
81: 10
82: 83
83: 233
84: 138
85: 148
86: 38
87: 39
88: 22
89: 40
90: 105
91: 20
92: 69
93: 26
94: 69
95: 173
96: 63
97: 38
98: 57
99: 151
100: 97
101: 28
102: 26
103: 83
104: 117
105: 56
106: 170
107: 542
108: 149
109: 22
110: 80
111: 81
112: 40
113: 41
114: 31
115: 54
116: 30
117: 48
118: 92
119: 16
120: 109
121: 139
122: 114
123: 84
124: 61
125: 30
126: 103
127: 79
128: 41
129: 26
130: 124
131: 35
132: 72
133: 57
134: 59
135: 184
136: 24
137: 236
138: 53
139: 137
140: 79
141: 58
142: 163
143: 106
144: 50
145: 226
146: 46
147: 117
148: 88
149: 56
150: 27
151: 156
152: 26
153: 62
154: 38
155: 65
156: 112
157: 45
158: 30
159: 60
160: 55
161: 58
162: 95
163: 19
164: 49
165: 92
166: 197
167: 41
168: 32
169: 82
170: 71

In [37]:
import json
from bs4 import BeautifulSoup

def extract_merged_snippets(data, padding=100):
    merged_snippets = {}

    for doc in data:
        doc_id = doc['id']
        merged_snippets[doc_id] = []

        raw_html = doc["data"]["html"]
        annotations = doc["annotations"][0]["result"]

        # Clean HTML to plain text
        soup = BeautifulSoup(raw_html, 'html.parser')
        plain_text = soup.get_text()

        # Collect and sort spans
        spans = []
        for ann in annotations:
            value = ann.get("value", {})
            if "globalOffsets" not in value or "text" not in value:
                continue

            start = value["globalOffsets"]["start"]
            end = value["globalOffsets"]["end"]
            spans.append((max(0, start - padding), min(len(plain_text), end + padding)))

        spans.sort()

        # Merge overlapping/adjacent spans
        merged = []
        for span in spans:
            if not merged:
                merged.append(span)
            else:
                last_start, last_end = merged[-1]
                curr_start, curr_end = span
                if curr_start <= last_end:
                    merged[-1] = (last_start, max(last_end, curr_end))
                else:
                    merged.append(span)

        # Extract text for merged spans
        for start, end in merged:
            snippet = plain_text[start:end]
            merged_snippets[doc_id].append(snippet)

    return merged_snippets

# Example usage
snippets = extract_merged_snippets(merged_, padding=100)

for doc_id, s_list in snippets.items():
    print(f'\nDoc ID: {doc_id}')
    for i, snippet in enumerate(s_list[:5], 1):
        print(f"\nSnippet {i}:\n{snippet}\n{'-'*40}")

Doc ID: 1

Snippet 1:
agreement.htm
EX-10.1




DocumentEXHIBIT 10.1CREDIT AGREEMENTdated as of January 10, 2022amongFRANKLIN RESOURCES, INC.,as the Borrower,BANK OF AMERICA, N.A.,as Administrative Agent,andthe Lenders party heretoBANK OF AMERICA, N.A.,asSole Lead Arranger and Sole Bookrunner                TABLE OF CONTENTSSectionPageARTICLE IDEFINITIONS AND ACCOUNTING TERMS11.01Defined Terms11.0
----------------------------------------

Snippet 2:
is CREDIT AGREEMENT (“Agreement”) is entered into as of January 10, 2022, among FRANKLIN RESOURCES, INC., a Delaware corporation (the “Borrower”), each lender from time to time party hereto (collectively, the “Lenders” and individually, a “Lender”), and BANK OF AMERICA, N.A., as Administrative Agent.The Borrower has requested that the Lenders provide a revolving credit facility, and the Lenders are willing to do so o
----------------------------------------

Snippet 3:
Affiliate of an entity that administers or manages a Lender.“Arranger” means Bank of America, N.A., an affiliate of BofA Securities, Inc., in its capacity as sole lead arranger and sole bookrunner.“Assignment and Assumption” means an assignment and assumption entered into by a Lender and an Eligible Assignee (with the
----------------------------------------

Snippet 4:
k Constant            Name:  Mark ConstantTitle:  Vice President and Treasurer[Signature Page to Credit Agreement]BANK OF AMERICA, N.A.,as Administrative AgentBy:  /s/    Alexandra M. Knights            Name:  Alexandra M. KnightsTitle:    Authorized Signatory[Signature Page to Credit Agreement]BANK OF AMERICA, N.A., as a LenderBy:  /s/    Alexandra M. Knights            Name:  Alexandra M. KnightsTitle:    Authorized Signatory[Signature Page to Credit Agreement]


----------------------------------------

Doc ID: 2

Snippet 1:
10.1

Exhibit 10.1
EXECUTION VERSION

CREDIT AGREEMENT  DATED
AS OF JANUARY 14, 2022  AMONG
DICKS SPORTING GOODS, INC.,
as the Borrower,  THE
LENDERS FROM TIME TO TIME PARTIES HERETO,  and
WELLS FARGO BANK, NATIONAL ASSOCIATION,
as Administrative Agent and an Issuing Lender
WELLS FARGO SECURITIES, LLC,
and  BOFA SECURITIES,
INC.,  as Joint Lead Arrangers and Joint Bookrunners
BANK OF AMERICA, N.A.,
as Syndication Agent
PNC BANK, NATIONAL ASSOCIATION,
TD SECURITIES (USA)
----------------------------------------

Snippet 2:
(c) an entity or an Affiliate of an entity that administers or manages a Lender.  Arrangers means Wells Fargo
Securities, LLC and BofA Securities, Inc., in their capacity as Joint Lead Arrangers.  Article means an Article of this
Agreement unless another document is specifically referenced.
----------------------------------------

Snippet 3:
.0% of the voting power of all of the Voting Stock of such person.  Co-Documentation Agents means PNC Bank, National Association, TD Securities (USA) LLC, New York Branch and U.S. Bank National Association, in their capacity as
co-documentation agents for the Lenders, and not in their individual capacity as Lenders.
  9




Code means the Inter
----------------------------------------

Snippet 4:
fteen percent (15%) of the Consolidated Assets of the Borrower and its Subsidiaries on such date.
Syndication Agent means BofA Securities, Inc., in its capacity as syndication agent for the Lenders, and not in its
individual capacity as a Lend
----------------------------------------

Snippet 5:
WHEREOF, the parties hereto have executed this Agreement as of the date first
written above.




DICKS SPORTING GOODS, INC.,

as the Borrower



/s/ Navdeep Gupta

Name: Navdeep Gupta

Title: Executive Vice President and Chief Financial Officer
 [Signature Page to Credit Agreement]














ADMINISTRATIVE AGENT:



    WELLS FARGO BANK, NATIONAL ASSOCIATION





    as the Administrative Agent, as an Issuing Lender and as a Lender














By:

/s/ Carl Hinrichs





Name:

Carl Hinrichs





Title:

Director
 [Signature Page to Credit Agreement]











BANK OF AMERICA, N.A., as an Issuing Lender and as a Lender









By:

/s/ Anthony Hoye






Name:

Anthony Hoye

Title:

Director
 [Signature Page to Credit Agreement]











PNC BANK, NATIONAL ASSOCIATION,

as a Lender









By:

/s/ Mary F. Molnar

Name:

Mary F. Molnar

Title:

Senior Vice President [Signature Page to Credit
Agreement]











 THE TORONTO-DOMINION BANK, NEW YORK
BRANCH, as a Lender




By:

/s/ Michael Borowiecki

Name:

Michael Borowiecki

Title:

Authorized Signatory
 [Signature Page to Credit Agreement]











U. S. BANK NATIONAL ASSOCIATION,as a Lender




By:

/s/ Adam J. Kultgen

Name:

Adam J. Kultgen

Title:

Vice President
 [Signature Page to Credit Agreement]











 CAPITAL ONE, N.A., as a
Lender




By:

/s/ Paul Isaac

Name:

Paul Isaac

Title:

Duly Authorized Signatory
 [Signature Page to Credit Agreement]











FIFTH THIRD BANK, NATIONAL ASSOCIATIONas a Lender




By:

/s/ Mary Ramsey

Name:

Mary Ramsey

Title:

Managing Director, SVP
 [Signature Page to Credit Agreement]











TRUIST BANK,as a Lender




By:

/s/ Alysa Trakas

Name:

Alysa Trakas

Title:

Director
 [Signature Page to Credit Agreement]











CITIZENS BANK, N.A.,as a Lender




By:

/s/ Carl S. Tabacjar, Jr

Name:

Carl S. Tabacjar, Jr

Title:

Senior Vice President
 [Signature Page to Credit Agreement]











HSBC BANK USA, N.A.,as a Lender




By:

/s/ Jaime Mariano

Name:

Jaime Mariano

Title:

Senior Vice President #21440
 [Signature Page to Credit Agreement]











 THE HUNTINGTON NATIONAL BANK,
as a Lender




By:

/s/ Phil Andresen

Name:

Phil Andresen

Title:

Vice President
 [Signature Page to Credit Agreement]



----------------------------------------

Doc ID: 3

Snippet 1:
w Term Facility
CUSIP Number: 86613YAC7

CREDIT AGREEMENT

Dated as of January 13, 2022

among

SUMMIT JV MR 2, LLC,

SUMMIT JV MR 3, LLC

and

SUMMIT NCI NOLA BR 184, LLC

as Borrowers,

SUMMIT HOSPITALITY JV, LP

as Parent,

CERTAIN SUBSIDIARIES OF THE BORROWERS
FROM TIME TO TIME PARTY HERETO,

as Guarantors,

THE INITIAL LENDERS NAMED HEREIN,

as Initial Lenders,

BANK OF AMERICA, N.A.,

as Administrative Agent,

and

BofA SECURITIES, INC.

and
WELLS FARGO SECURITIES, LLC,

as Joint Lead Arrangers and
as Joint Bookrunners

WELLS FARGO BANK, NATIONAL ASSOCIATION, as

Syndication Agent







T A B L E O F C O N T E N
T S



Section
Page



Article I
DEFINITIONS AND ACCOUNTING T
----------------------------------------

Snippet 2:
er in such Hedge
Agreements (which may include a Lender or any Affiliate of a Lender).

“Syndication
Agent” means Wells Fargo Bank, National Association, in its capacity as syndication agent.

“Synthetic
Debt” means, with respect to any Person as of any date of
----------------------------------------

Snippet 3:
presentatives thereunto duly authorized, as of the
date first above written.




BORROWERS:





SUMMIT JV MR 2, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT JV MR 3, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI NOLA BR 184, LLC,
 a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary



 PARENT:




SUMMIT HOSPITALITY JV, LP,
a Delaware limited partnership





By:
Summit Hotel GP 2, LLC,
a Delaware limited liability company


Its:
general partner







By:
/s/ Christopher Eng



Name:     Christopher Eng



Title:       Secretary


[Signature Page to Credit
Agreement - Summit JV Credit Agreement]








GUARANTORS:




SUMMIT HOSPITALITY SUBJV, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI MASTER TRS, INC.,
a Delaware corporation



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 156-159, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 160, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 161, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary


[Signature Page to Credit
Agreement - Summit JV Credit Agreement]










SUMMIT NCI JV BR 162, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 163-164, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 165, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 166, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 167-168, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 169, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary


[Signature Page to Credit
Agreement - Summit JV Credit Agreement]










SUMMIT NCI JV BR 171, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 172, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 173, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 174, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 175, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 176, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary


[Signature Page to Credit
Agreement - Summit JV Credit Agreement]










SUMMIT NCI JV BR 177, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 178, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 179, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 180, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 181, LLC,
a Delaware limited liability company



By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary





SUMMIT NCI JV BR 182-183, LLC,
a Delaware limited liability company




By:/s/ Christopher Eng
  Name:     Christopher Eng

  Title:       Secretary


[Signature Page to Credit
Agreement - Summit JV Credit Agreement]










SUMMIT NCI JV 158, LLC,
a Delaware limited liability company





By:
Summit NCI JV BR 156-159, LLC,
 a Delaware limited liability company


Its:
sole member






----------------------------------------

Snippet 4:
                                   Eng

  Name:     Christopher Eng


  Title:       Secretary





SUMMIT NCI JV 159, LLC,
a Delaware limited liability company






By:
Supreme Bright Dallas II, LLC,
a Texas limited liability company


Its:
sole member





 By
----------------------------------------

Snippet 5:
                                 Eng

  Name:     Christopher Eng


  Title:       Secretary





SUMMIT NCI JV 160, LLC,
 a Delaware limited liability company






By:
Summit NCI JV BR 160, LLC,
 a Delaware limited liability company


Its:
sole member





 By:/s
----------------------------------------

Doc ID: 4

Snippet 1:
 Holdings,  GOLDMAN SACHS BANK USA,
as Administrative Agent, Swing Line Lender,  L/C Issuer, Joint Lead Arranger and Joint Bookrunner,  THE OTHER LENDERS PARTY
HERETO,  J.P. MORGAN SECURITIES LLC,  as Joint Lead Arranger, Joint Bookrunner and Syndication Agent,  and
BARCLAYS BANK PLC,
MERRILL LYNCH, PIERCE, FENNER & SMITH INCORPORATED and  CREDIT SUISSE SECURITIES (USA) LLC,  as Joint Bookrunners and Co-Documentation
Agents



Exhibit 10.1  TABLE OF CONTENTS














Page


 ARTICLE I Definitions and Ac
----------------------------------------

Snippet 2:
ave caused this Agreement to be duly executed
as of the date first above written.






 BRIGHT HORIZONS FAMILY SOLUTIONS LLC, as Borrower




 By:

/s/ David Lissy



Name:  David Lissy



Title:    Chief Executive Officer











 BRIGHT HORIZONS CAPITAL CORP., as Holdings




 By:

/s/ David Lissy



Name:  David Lissy



Title:    Chief Executive Officer




   [Credit Agreement]










 GOLDMAN SACHS BANK USA, as Administrative Agent, Swing Line Lender and L/C Issuer




 By:

/s/ Robert Ehudin



Name:  Robert Ehudin



Title:    Authorized Signatory








   [Credit Agreement]










 GOLDMAN SACHS BANK USA, as Term Lender and Revolving Credit Lender




 By:

/s/ Robert Ehudin



Name:  Robert Ehudin



Title:    Authorized Signatory








   [Credit Agreement]










 JPMORGAN CHASE BANK N.A., as Revolving Credit Lender




 By:

/s/ Sarah L. Freedman



Name:  Sarah L. Freedman



Title:    Executive Director




   [Credit Agreement]










 BARCLAYS BANK PLC, as Revolving Credit Lender




 By:

/s/ Ronnie Glen



Name:  Ronnie Glen



Title:    Vice President




   [Credit Agreement]










 BANK OF AMERICA, N.A., as Revolving Credit Lender




 By:

/s/ Frank Byrne



Name:  Frank Byrne



Title:    Vice President




   [Credit Agreement]










 CREDIT SUISSE AG, CAYMAN ISLANDS BRANCH, as Revolving Credit Lender




 By:

/s/ John Toronto



Name:  John Toronto



Title:    Managing Director












 By:

/s/ Wei-Jen Yuan



Name:  Wei-Jen Yuan



Title:    Associate
   [Credit Agreement]



SCHEDULE 1.01B  TO CREDIT AGREEMENT  Certain Security Interests and Guarantees


----------------------------------------

Snippet 3:
tices  Administrative Agent  Goldman Sachs Bank USA  200 West Street  New York, New York  Telephone: (212) 902-1099
Facsimile: (917) 977-3966  Email:
gs-sbdagency-borrowernotices@ny.email.gs.com  Swing Line Lender  Goldman Sachs Bank U
----------------------------------------

Snippet 4:
ny.email.gs.com  L/C Issuer  Goldman Sachs Bank USA  6011 Connection Drive
Irving, Texas 75039  Telephone:
(972) 368-2734  Facsimile: (917) 977-4587  Email: Gs-loc-operations@ny.email.gs.com  Attention: Loan Operations / Servicing  Letter o
----------------------------------------

Snippet 5:
664  Borrower  Bright Horizons Family Solutions LLC  200 Talcott Avenue South
P.O. Box 9177  Watertown, MA 02471-9177
 Telephone: (617) 673-8041
Facsimile: (617) 673-8653  Email:
jplocica@brighthorizons.com  Attention: Jim Plocica


with a copy to:  200 Talcott Avenue South  P.O. Box 9177  Watertown, MA 02471-9177  Telephone: (617) 673-8000
Facsimile: (617) 673-8653  Email
----------------------------------------

Doc ID: 5

Snippet 1:
EDIT




Exhibit 10.1 Unsecured line of credit
CREDIT AGREEMENTDated as of January 31, 2013amongACADIA REALTY LIMITED PARTNERSHIP,as the Borrower,andACADIA REALTY TRUSTandCERTAIN SUBSIDIARIES OFACADIA REALTY LIMITED PARTNERSHIPFROM TIME TO TIME PARTY HERETO,as GuarantorsBANK OF AMERICA, N.A.,as Administrative Agent, Swing Line Lender,L/C Issuer and as a Lender,PNC BANK, NATIONAL ASSOCIATIONandWELLS FARGO BANK, NATIONAL ASSOCIATION,as Co-Documentation AgentsandThe Other Lenders Party HeretoMERRILL LYNCH, PIERCE, FENNER & SMITH INCORPORATED,as a Joint Lead Arranger and Sole BookrunnerandPNC BANK, NATIONAL ASSOCIATIONandWELLS FARGO SECURITIES, LLC,as Joint Lead Arrangers TABLE OF CONTENTSSection                                                PageArticle I. DEFINITIONS AND A
----------------------------------------

Snippet 2:
(this “Agreement”) is entered into as of January 31, 2013, among ACADIA REALTY LIMITED PARTNERSHIP, a Delaware limited partnership (the “Borrower”), ACADIA REALTY TRUST, a Maryland real estate investment trust (the “REIT”) and certain subsidiaries of the Borrower from time to time party hereto, as Guarantors, each
----------------------------------------

Snippet 3:
dentACADIA 1520 MILWAUKEE AVENUE LLC, a Delaware limited liability companyBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA 28 JERICHO TURNPIKE LLC, a Delaware limited liability companyBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA 2914 THIRD AVENUE LLC, a Delaware limited liability companyBy: /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA 5-7 EAST 17TH STREET LLC, a Delaware limited liability companyBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA 83 SPRING STREET LLC, a Delaware limited liability companyBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA BARTOW AVENUE LLC, a Delaware limited liability companyBy: /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA CHESTNUT LLC, a Delaware limited liability companyBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA GOLD COAST LLC, a Delaware limited liability companyBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA MAD RIVER PROPERTY LLC, a Delaware limited liability companyBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA MERCER STREET LLC, a Delaware limited liability companyBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA RUSH WALTON LLC, a Delaware limited liability companyBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA TOWN LINE LLC, a Connecticut limited liability companyBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA WEST 54TH STREET LLC, a Delaware limited liability companyBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA WEST SHORE EXPRESSWAY LLC, a Delaware limited liability companyBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentMARK PLAZA FIFTY L.P., a Pennsylvania limited partnershipBy:  ACADIA MARK PLAZA LLC, its General PartnerBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentACADIA MARK PLAZA LLC, a Delaware limited liability companyBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentRD ABINGTON ASSOCIATES LIMITED PARTNERSHIP, a Delaware limited partnershipBy:  ACADIA PROPERTY HOLDINGS, LLC, its General PartnerBy:  /s/ Robert Masters    Name:  Robert MastersTitle:    Senior Vice PresidentRD ABSECON ASSOCIATES, L.P, a Delaware limited partnershi
----------------------------------------

Snippet 4:

# Reorganizing

In [6]:
merged_ = read_json('final_merged.json')

In [7]:
for merged_doc in merged_:
    print(merged_doc['id'])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170

In [51]:
merged_[0]

{'id': 1,
 'annotations': [{'id': 1,
   'completed_by': 1,
   'result': [{'value': {'start': '/document[1]/text[1]/div[886]/font[1]/text()[1]',
      'startOffset': 0,
      'end': '/document[1]/text[1]/div[886]/font[1]/text()[1]',
      'endOffset': 24,
      'globalOffsets': {'start': 305599, 'end': 305623},
      'text': 'FRANKLIN RESOURCES, INC.',
      'hypertextlabels': ['Organization Name']},
     'id': 'aaaaaaaaaa',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[890]/font[1]/text()[1]',
      'startOffset': 7,
      'end': '/document[1]/text[1]/div[890]/font[1]/text()[1]',
      'endOffset': 20,
      'globalOffsets': {'start': 305669, 'end': 305682},
      'text': 'Mark Constant',
      'hypertextlabels': ['Person Name']},
     'id': 'aaaaaaaaab',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[891]/font[1]/text()[1]',
      'startOffset': 8,
      'end': '/document[1]/text[1]/div[891]/font[1]/text()[1]',
      'endOffset': 22,
      'globalOffsets': {'start': 305690, 'end': 305704},
      'text': 'Vice President',
      'hypertextlabels': ['Person Position']},
     'id': 'aaaaaaaaac',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[891]/font[1]/text()[1]',
      'startOffset': 27,
      'end': '/document[1]/text[1]/div[891]/font[1]/text()[1]',
      'endOffset': 36,
      'globalOffsets': {'start': 305709, 'end': 305718},
      'text': 'Treasurer',
      'hypertextlabels': ['Person Position']},
     'id': 'aaaaaaaaad',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[897]/font[1]/text()[1]',
      'startOffset': 0,
      'end': '/document[1]/text[1]/div[897]/font[1]/text()[1]',
      'endOffset': 21,
      'globalOffsets': {'start': 305758, 'end': 305779},
      'text': 'BANK OF AMERICA, N.A.',
      'hypertextlabels': ['Organization Name']},
     'id': 'aaaaaaaaae',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[897]/font[4]/text()[1]',
      'startOffset': 3,
      'end': '/document[1]/text[1]/div[897]/font[4]/text()[1]',
      'endOffset': 23,
      'globalOffsets': {'start': 305784, 'end': 305804},
      'text': 'Administrative Agent',
      'hypertextlabels': ['Organization Role']},
     'id': 'aaaaaaaaaf',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[901]/font[1]/text()[1]',
      'startOffset': 7,
      'end': '/document[1]/text[1]/div[901]/font[1]/text()[1]',
      'endOffset': 27,
      'globalOffsets': {'start': 305857, 'end': 305877},
      'text': 'Alexandra M. Knights',
      'hypertextlabels': ['Person Name']},
     'id': 'aaaaaaaaag',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[902]/font[1]/text()[1]',
      'startOffset': 10,
      'end': '/document[1]/text[1]/div[902]/font[1]/text()[1]',
      'endOffset': 30,
      'globalOffsets': {'start': 305887, 'end': 305907},
      'text': 'Authorized Signatory',
      'hypertextlabels': ['Person Position']},
     'id': 'aaaaaaaaah',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[907]/font[1]/text()[1]',
      'startOffset': 0,
      'end': '/document[1]/text[1]/div[907]/font[1]/text()[1]',
      'endOffset': 21,
      'globalOffsets': {'start': 305946, 'end': 305967},
      'text': 'BANK OF AMERICA, N.A.',
      'hypertextlabels': ['Organization Name']},
     'id': 'aaaaaaaaai',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[908]/font[1]/text()[1]',
      'startOffset': 5,
      'end': '/document[1]/text[1]/div[908]/font[1]/text()[1]',
      'endOffset': 11,
      'globalOffsets': {'start': 305974, 'end': 305980},
      'text': 'Lender',
      'hypertextlabels': ['Organization Role']},
     'id': 'aaaaaaaaaj',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[912]/font[1]/text()[1]',
      'startOffset': 7,
      'end': '/document[1]/text[1]/div[912]/font[1]/text()[1]',
      'endOffset': 27,
      'globalOffsets': {'start': 306033, 'end': 306053},
      'text': 'Alexandra M. Knights',
      'hypertextlabels': ['Person Name']},
     'id': 'aaaaaaaaak',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[913]/font[1]/text()[1]',
      'startOffset': 10,
      'end': '/document[1]/text[1]/div[913]/font[1]/text()[1]',
      'endOffset': 30,
      'globalOffsets': {'start': 306063, 'end': 306083},
      'text': 'Authorized Signatory',
      'hypertextlabels': ['Person Position']},
     'id': 'aaaaaaaaal',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
      'startOffset': 8,
      'end': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
      'endOffset': 29,
      'globalOffsets': {'start': 8028, 'end': 8049},
      'text': 'Bank of America, N.A.',
      'hypertextlabels': ['Organization Name']},
     'id': 'aaaaaaaaam',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
      'startOffset': 94,
      'end': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
      'endOffset': 99,
      'globalOffsets': {'start': 8114, 'end': 8119},
      'text': 'lead ',
      'hypertextlabels': ['Organization Sub-Role']},
     'id': 'aaaaaaaaan',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
      'startOffset': 99,
      'end': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
      'endOffset': 108,
      'globalOffsets': {'start': 8119, 'end': 8128},
      'text': 'arranger ',
      'hypertextlabels': ['Organization Role']},
     'id': 'aaaaaaaaao',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
      'startOffset': 117,
      'end': '/document[1]/text[1]/div[85]/font[3]/text()[1]',
      'endOffset': 127,
      'globalOffsets': {'start': 8137, 'end': 8147},
      'text': 'bookrunner',
      'hypertextlabels': ['Organization Role']},
     'id': 'aaaaaaaaap',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[65]/font[4]/text()[1]',
      'startOffset': 0,
      'end': '/document[1]/text[1]/div[65]/font[4]/text()[1]',
      'endOffset': 8,
      'globalOffsets': {'start': 4991, 'end': 4999},
      'text': 'Borrower',
      'hypertextlabels': ['Organization Role']},
     'id': 'aaaaaaaaaq',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[65]/font[3]/text()[1]',
      'startOffset': 49,
      'end': '/document[1]/text[1]/div[65]/font[3]/text()[1]',
      'endOffset': 73,
      'globalOffsets': {'start': 4936, 'end': 4960},
      'text': 'FRANKLIN RESOURCES, INC.',
      'hypertextlabels': ['Organization Name']},
     'id': 'aaaaaaaaar',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[65]/font[9]/text()[1]',
      'startOffset': 8,
      'end': '/document[1]/text[1]/div[65]/font[9]/text()[1]',
      'endOffset': 29,
      'globalOffsets': {'start': 5110, 'end': 5131},
      'text': 'BANK OF AMERICA, N.A.',
      'hypertextlabels': ['Organization Name']},
     'id': 'aaaaaaaaas',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[65]/font[11]/text()[1]',
      'startOffset': 3,
      'end': '/document[1]/text[1]/div[65]/font[11]/text()[1]',
      'endOffset': 23,
      'globalOffsets': {'start': 5136, 'end': 5156},
      'text': 'Administrative Agent',
      'hypertextlabels': ['Organization Role']},
     'id': 'aaaaaaaaat',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[10]/font[1]/text()[1]',
      'startOffset': 0,
      'end': '/document[1]/text[1]/div[10]/font[1]/text()[1]',
      'endOffset': 24,
      'globalOffsets': {'start': 127, 'end': 151},
      'text': 'FRANKLIN RESOURCES, INC.',
      'hypertextlabels': ['Organization Name']},
     'id': 'aaaaaaaaau',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[12]/font[1]/text()[1]',
      'startOffset': 0,
      'end': '/document[1]/text[1]/div[12]/font[1]/text()[1]',
      'endOffset': 21,
      'globalOffsets': {'start': 168, 'end': 189},
      'text': 'BANK OF AMERICA, N.A.',
      'hypertextlabels': ['Organization Name']},
     'id': 'aaaaaaaaav',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[16]/font[1]/text()[1]',
      'startOffset': 0,
      'end': '/document[1]/text[1]/div[16]/font[1]/text()[1]',
      'endOffset': 21,
      'globalOffsets': {'start': 243, 'end': 264},
      'text': 'BANK OF AMERICA, N.A.',
      'hypertextlabels': ['Organization Name']},
     'id': 'aaaaaaaaaw',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[11]/font[1]/text()[1]',
      'startOffset': 7,
      'end': '/document[1]/text[1]/div[11]/font[1]/text()[1]',
      'endOffset': 15,
      'globalOffsets': {'start': 159, 'end': 167},
      'text': 'Borrower',
      'hypertextlabels': ['Organization Role']},
     'id': 'aaaaaaaaax',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[12]/font[2]/text()[1]',
      'startOffset': 3,
      'end': '/document[1]/text[1]/div[12]/font[2]/text()[1]',
      'endOffset': 23,
      'globalOffsets': {'start': 194, 'end': 214},
      'text': 'Administrative Agent',
      'hypertextlabels': ['Organization Role']},
     'id': 'aaaaaaaaay',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[14]/font[1]/text()[1]',
      'startOffset': 4,
      'end': '/document[1]/text[1]/div[14]/font[1]/text()[1]',
      'endOffset': 11,
      'globalOffsets': {'start': 222, 'end': 229},
      'text': 'Lenders',
      'hypertextlabels': ['Organization Role']},
     'id': 'aaaaaaaaaz',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[18]/font[1]/text()[1]',
      'startOffset': 10,
      'end': '/document[1]/text[1]/div[18]/font[1]/text()[1]',
      'endOffset': 18,
      'globalOffsets': {'start': 277, 'end': 285},
      'text': 'Arranger',
      'hypertextlabels': ['Organization Role']},
     'id': 'aaaaaaaaaA',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[18]/font[1]/text()[1]',
      'startOffset': 28,
      'end': '/document[1]/text[1]/div[18]/font[1]/text()[1]',
      'endOffset': 38,
      'globalOffsets': {'start': 295, 'end': 305},
      'text': 'Bookrunner',
      'hypertextlabels': ['Organization Role']},
     'id': 'aaaaaaaaaB',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'value': {'start': '/document[1]/text[1]/div[18]/font[1]/text()[1]',
      'startOffset': 5,
      'end': '/document[1]/text[1]/div[18]/font[1]/text()[1]',
      'endOffset': 9,
      'globalOffsets': {'start': 272, 'end': 276},
      'text': 'Lead',
      'hypertextlabels': ['Organization Sub-Role']},
     'id': 'aaaaaaaaaC',
     'from_name': 'ner',
     'to_name': 'text',
     'type': 'hypertextlabels',
     'origin': 'manual'},
    {'from_id': 'aaaaaaaaam',
     'to_id': 'aaaaaaaaao',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaam',
     'to_id': 'aaaaaaaaap',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaao',
     'to_id': 'aaaaaaaaan',
     'type': 'relation',
     'direction': 'left'},
    {'from_id': 'aaaaaaaaar',
     'to_id': 'aaaaaaaaaq',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaab',
     'to_id': 'aaaaaaaaac',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaab',
     'to_id': 'aaaaaaaaad',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaac',
     'to_id': 'aaaaaaaaaa',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaad',
     'to_id': 'aaaaaaaaaa',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaae',
     'to_id': 'aaaaaaaaaf',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaag',
     'to_id': 'aaaaaaaaah',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaah',
     'to_id': 'aaaaaaaaae',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaai',
     'to_id': 'aaaaaaaaaj',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaak',
     'to_id': 'aaaaaaaaal',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaal',
     'to_id': 'aaaaaaaaai',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaas',
     'to_id': 'aaaaaaaaat',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaaC',
     'to_id': 'aaaaaaaaaA',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaaw',
     'to_id': 'aaaaaaaaaA',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaaw',
     'to_id': 'aaaaaaaaaB',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaaw',
     'to_id': 'aaaaaaaaaz',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaav',
     'to_id': 'aaaaaaaaay',
     'type': 'relation',
     'direction': 'right'},
    {'from_id': 'aaaaaaaaau',
     'to_id': 'aaaaaaaaax',
     'type': 'relation',
     'direction': 'right'}],
   'was_cancelled': False,
   'ground_truth': False,
   'created_at': '2025-01-27T03:00:26.800949Z',
   'updated_at': '2025-01-27T03:00:26.800997Z',
   'draft_created_at': None,
   'lead_time': 1278.878,
   'prediction': {},
   'result_count': 0,
   'unique_id': '9f582d92-3bdf-48db-8c1f-5af4e40a9793',
   'import_id': 1,
   'last_action': None,
   'task': 1,
   'project': 142,
   'updated_by': None,
   'parent_prediction': None,
   'parent_annotation': None,
   'last_created_by': None}],
 'file_upload': '081f8497-semi_cleaned_docs.json',
 'drafts': [],
 'predictions': [],

In [5]:
htmls = read_html_files('./raw/')

In [6]:
mapping = {}
for i in range(len(merged_)):
    error = True
    for html_id, html_content in htmls.items():
        if merged_[i]['data']['html'] == html_content:
            if html_id[0] not in mapping:
                mapping[html_id[0]] = []
            mapping[html_id[0]].append(merged_[i]['id'])
            error = False
            break
    if error:
        print(merged_[i]['id'])

81

In [7]:
for year, ids in mapping.items():
    print(year, len(ids))

2022 17
2013 17
2014 16
2018 17
2019 17
2020 17
2021 17
2015 17
2016 17
2017 17

In [8]:
mapping[2014].append(81)

In [9]:
for year, ids in mapping.items():
    print(year, len(ids))

2022 17
2013 17
2014 17
2018 17
2019 17
2020 17
2021 17
2015 17
2016 17
2017 17

In [10]:
dev_set = []
test_set = []
proprietary_set = []
for _, doc_ids in mapping.items():
    dev_set += doc_ids[:4]
    test_set += doc_ids[4:]
    proprietary_set += doc_ids[4:5]

In [11]:
sorted(dev_set)

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 18,
 19,
 20,
 21,
 22,
 23,
 28,
 29,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 44,
 46,
 48,
 50,
 63,
 64]

In [12]:
sorted(test_set)

[9,
 17,
 24,
 25,
 26,
 27,
 30,
 31,
 43,
 45,
 47,
 49,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170]

In [13]:
sorted(proprietary_set)

[9, 17, 25, 43, 45, 47, 51, 60, 65, 66]

In [14]:
dev_docs = []
test_docs = []
proprietary_docs = []
for i in range(len(merged_)):
    if merged_[i]['id'] in dev_set:
        dev_docs.append(merged_[i])
    else:
        test_docs.append(merged_[i])
        if merged_[i]['id'] in proprietary_set:
            proprietary_docs.append(merged_[i])

In [15]:
save_json(dev_docs, 'docs_dev.json')
save_json(test_docs, 'docs_test.json')
save_json(proprietary_docs, 'docs_proprietary.json')

# QAs

In [16]:
import pandas as pd

qa_pairs = pd.read_csv('L5.csv')
qa_pairs.info()
qa_pairs.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   document_number     450 non-null    int64
 1   question            450 non-null    object
 2   answer              450 non-null    object
 3   num_hops            450 non-null    int64
 4   num_set_operations  450 non-null    int64
 5   multiple_answers    450 non-null    object
dtypes: int64(3), object(3)
memory usage: 21.2+ KB

,document_number,question,answer,num_hops,num_set_operations,multiple_answers
0,139,who is the senior vice president but not chief...,jay a. brown,3,2,0
1,139,who is the vice president but not authorized s...,michael king,3,2,0
2,139,who is the vice president but not authorized s...,michael king,3,2,0
3,139,who is the vice president but not authorized s...,michael king,3,2,0
4,139,who is the vice president but not authorized s...,michael king,3,2,0

In [17]:
dev_qas = qa_pairs[qa_pairs['document_number'].isin(dev_set)]
dev_qas.info()
dev_qas.head()

<class 'pandas.core.frame.DataFrame'>
Index: 157 entries, 86 to 344
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   document_number     157 non-null    int64
 1   question            157 non-null    object
 2   answer              157 non-null    object
 3   num_hops            157 non-null    int64
 4   num_set_operations  157 non-null    int64
 5   multiple_answers    157 non-null    object
dtypes: int64(3), object(3)
memory usage: 8.6+ KB

,document_number,question,answer,num_hops,num_set_operations,multiple_answers
86,11,who is the vice president but not treasurer of...,john j. tus,3,2,0
87,11,who is the vice president but not treasurer of...,john j. tus,3,2,0
90,38,who is the executive director of the company w...,dave katz,3,2,0
123,41,who is the director of the company which is th...,john dillon,3,2,0
124,41,who is the director of the company which is th...,john dillon,3,2,0

In [18]:
test_qas = qa_pairs[qa_pairs['document_number'].isin(test_set)]
test_qas.info()
test_qas.head()

<class 'pandas.core.frame.DataFrame'>
Index: 293 entries, 0 to 449
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   document_number     293 non-null    int64
 1   question            293 non-null    object
 2   answer              293 non-null    object
 3   num_hops            293 non-null    int64
 4   num_set_operations  293 non-null    int64
 5   multiple_answers    293 non-null    object
dtypes: int64(3), object(3)
memory usage: 16.0+ KB

,document_number,question,answer,num_hops,num_set_operations,multiple_answers
0,139,who is the senior vice president but not chief...,jay a. brown,3,2,0
1,139,who is the vice president but not authorized s...,michael king,3,2,0
2,139,who is the vice president but not authorized s...,michael king,3,2,0
3,139,who is the vice president but not authorized s...,michael king,3,2,0
4,139,who is the vice president but not authorized s...,michael king,3,2,0

In [19]:
the_rest = qa_pairs[(~qa_pairs['document_number'].isin(test_set)) & (~qa_pairs['document_number'].isin(dev_set))]
the_rest.info()
the_rest.head()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   document_number     0 non-null      int64
 1   question            0 non-null      object
 2   answer              0 non-null      object
 3   num_hops            0 non-null      int64
 4   num_set_operations  0 non-null      int64
 5   multiple_answers    0 non-null      object
dtypes: int64(3), object(3)
memory usage: 0.0+ bytes

Empty DataFrame
Columns: [document_number, question, answer, num_hops, num_set_operations, multiple_answers]
Index: []

In [20]:
proprietary_qas = qa_pairs[qa_pairs['document_number'].isin(proprietary_set)]
proprietary_qas.info()
proprietary_qas.head()

<class 'pandas.core.frame.DataFrame'>
Index: 101 entries, 112 to 434
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   document_number     101 non-null    int64
 1   question            101 non-null    object
 2   answer              101 non-null    object
 3   num_hops            101 non-null    int64
 4   num_set_operations  101 non-null    int64
 5   multiple_answers    101 non-null    object
dtypes: int64(3), object(3)
memory usage: 5.5+ KB

,document_number,question,answer,num_hops,num_set_operations,multiple_answers
112,66,who is the authorized signer of the company wh...,james riley,3,2,0
113,66,who is the authorized signer of the company wh...,james riley,3,2,0
114,66,who is the authorized signer of the company wh...,james riley,3,2,0
116,9,who is the senior vice president but not chief...,mark e. newman,3,2,0
117,9,who is the senior vice president but not chief...,mark e. newman,3,2,0

### Test

In [21]:
test_qas['document_number'].value_counts().to_dict()

{60: 71,
 166: 15,
 135: 15,
 107: 14,
 66: 13,
 94: 11,
 121: 10,
 83: 8,
 151: 8,
 147: 7,
 51: 6,
 96: 6,
 130: 6,
 169: 6,
 61: 5,
 47: 5,
 84: 5,
 139: 5,
 145: 5,
 153: 5,
 77: 4,
 162: 4,
 65: 4,
 68: 4,
 115: 4,
 86: 3,
 142: 3,
 59: 3,
 137: 3,
 124: 2,
 87: 2,
 90: 2,
 72: 2,
 128: 2,
 156: 2,
 9: 2,
 165: 2,
 140: 2,
 155: 2,
 106: 2,
 111: 2,
 144: 2,
 26: 1,
 127: 1,
 58: 1,
 54: 1,
 112: 1,
 89: 1,
 160: 1,
 99: 1,
 126: 1}

In [22]:
category_counts = test_qas['document_number'].value_counts()
valid_categories = category_counts[category_counts > 4].index
test_qas = test_qas[test_qas['document_number'].isin(valid_categories)]

In [23]:
test_qas['document_number'].value_counts().to_dict()

{60: 71,
 135: 15,
 166: 15,
 107: 14,
 66: 13,
 94: 11,
 121: 10,
 151: 8,
 83: 8,
 147: 7,
 169: 6,
 96: 6,
 51: 6,
 130: 6,
 145: 5,
 153: 5,
 61: 5,
 47: 5,
 84: 5,
 139: 5}

### Dev

In [24]:
dev_qas['document_number'].value_counts().to_dict()

{32: 117,
 35: 13,
 40: 8,
 22: 5,
 41: 3,
 11: 2,
 5: 2,
 23: 2,
 38: 1,
 42: 1,
 46: 1,
 3: 1,
 37: 1}

In [25]:
category_counts = dev_qas['document_number'].value_counts()
valid_categories = category_counts[category_counts > 4].index
dev_qas = dev_qas[dev_qas['document_number'].isin(valid_categories)]

In [26]:
dev_qas['document_number'].value_counts().to_dict()

{32: 117, 35: 13, 40: 8, 22: 5}

### Prop

In [27]:
proprietary_qas['document_number'].value_counts().to_dict()

{60: 71, 66: 13, 51: 6, 47: 5, 65: 4, 9: 2}

In [28]:
category_counts = proprietary_qas['document_number'].value_counts()
valid_categories = category_counts[category_counts > 4].index
proprietary_qas = proprietary_qas[proprietary_qas['document_number'].isin(valid_categories)]

In [29]:
proprietary_qas['document_number'].value_counts().to_dict()

{60: 71, 66: 13, 51: 6, 47: 5}

In [30]:
dev_qas.to_csv('L5_dev.csv')

In [31]:
test_qas.to_csv('L5_test.csv')

In [32]:
proprietary_qas.to_csv('L5_proprietary.csv')